= Framework agreement for the supply of the Full Induction Programme, to support National Roll-Out of the Early Career Framework

== THIS FRAMEWORK AGREEMENT

is made on 26 February 2021

== BETWEEN

[arabic]
. *THE SECRETARY OF STATE FOR EDUCATION* of Sanctuary Buildings, Great
Smith Street, London, SW1P 3BT acting as part of the Crown (“The
Department”); and
. *[REDACTED]* (Company No. *[REDACTED]* whose registered office is at
*[REDACTED]* (the "Contractor");
+
together, the "Parties"

== WHEREAS

[loweralpha]
. On 15 September 2020 the Department placed a contract notice in the
Official Journal of the European Union (the “OJEU Notice”) seeking
invitations to tender from service providers to be appointed to a
framework agreement for the supply of the Full Induction Programme, to
support National Roll-Out of the Early Career Framework;
. Following a selection and award process, the Contractor and five (5)
other providers (as set out in Schedule 6 (Framework Agreement
Providers) were awarded a place on the framework and requested to enter
into the Framework Agreement with the Department;
. The Contractor has agreed to enter into this Framework Agreement for
the supply of the Services to the Department.

== NOW IT IS HEREBY AGREED AS FOLLOWS:-

[arabic]
. Interpretations
[arabic]
.. As used in this Framework Agreement:-
[arabic]
... the terms and expressions set out in Schedule 1 shall have the
meanings set out therein;
... the masculine includes the feminine and the neuter;
... the singular includes the plural and vice versa; and
... the words “include”, “includes” and “including” are to be construed
as if they were immediately followed by the words “without limitation”.
.. In this Framework Agreement words and phrases with a first capital
letter (or any derivation thereof) shall have the meanings set out in
Schedule 1.
.. In this Framework Agreement except where the context otherwise
requires:-
[arabic]
... the masculine includes the feminine and vice-versa;
... the singular includes the plural and vice-versa;
... a reference in this Framework Agreement to any clause, sub-clause,
paragraph, schedule or annex is, except where it is expressly stated to
the contrary, a reference to such clause, sub-clause, paragraph,
schedule or annex of this Framework Agreement;
... any reference to this Framework Agreement or to any other document
shall include any permitted variation, amendment or supplement to such
document;
... any reference to any enactment, order, regulation, code, guidance or
other similar instrument shall be construed as a reference to the
enactment, order, regulation, code, guidance or instrument (including
any EU instrument) as amended, replaced, consolidated or re-enacted;
... a reference to a person includes firms, partnerships and
corporations and their successors and permitted assignees or
transferees;
... headings are for reference only;
... words preceding "include", "includes", "including" and "included"
shall be construed without limitation by the words which follow those
words;
... the Schedules to this Framework Agreement form part of this
Framework Agreement; and
... references to “the Parties” shall be to the parties to this
Framework Agreement.
.. No review, comment or approval by the Department under the provisions
of this Framework Agreement shall operate to exclude or limit the
Contractor ’s obligations or liabilities under this Framework Agreement
(or the Department’s rights under this Framework Agreement).
.. Precedence of Documentation
[arabic]
... In the event of any inconsistency between the provisions of the Main
Body of this Framework Agreement and the Schedules, or between any of
the Schedules, the conflict shall be resolved according to the following
descending order of priority:
[arabic]
.... the Main Body and Schedule 1 (Definitions);
.... Schedule 3 (the Specification); and
.... the remaining Schedules equally.

. SCOPE OF THIS FRAMEWORK AGREEMENT
[arabic]
.. This Framework Agreement shall take effect on the Commencement Date
and no Call-Off Contracts shall be entered into under it until that
date.
.. This Framework Agreement governs the overall relationship of the
Department with the Contractor with respect to the provision of the
Services. The Department is entitled (but not obliged) at any time
during the Contract Period to order Services in accordance with the
Ordering Procedures (Schedule 4).
.. The Framework Agreement is a multi-contractor arrangement and details
of all the contractors including the Contractor that have been appointed
to the Framework Agreement are set out in Schedule 6 (Framework
Agreement Providers).
.. Any Call-Off Contract shall be in the form of the standard Model
Call-Off Contract as set out in Schedule 2.
.. Any Call-Off Contract entered into under this Framework Agreement
shall commence on the date specified in that Call-Off Contract and shall
expire no later than the date specified in the Call-Off Contract.
.. The Contractor shall ensure that any Call-Off Contract entered into
under this Framework Agreement shall not:
[arabic]
... exceed the limits and scope of this Framework Agreement;
... include any terms and conditions that substantially amend or alter
the terms and conditions set out in the relevant Model Call-Off
Contract.
.. The Contractor shall invoice the Department for the Services it has
delivered in accordance with the terms of the Call-Off Contract.

. THE SERVICES
[arabic]
.. The Contractor shall make the Services available on and subject to
the terms of this Framework Agreement. When a Service is the subject of
an Order by the Department, it will be referred to in the ensuing
Call-Off Contract as an Ordered Service.
.. All Orders shall be placed in accordance with the Ordering Procedures
(Clause 0) and the payment for the Services will be calculated using the
Pricing Schedule (Schedule 7).
.. All Call-Off Contracts for the provision by the Contractor of Ordered
Services shall be on the terms and conditions prescribed in the Model
Call-Off Contract including where required any Additional Clauses as set
out in the Model Call-Off Contract.
.. The Department shall maintain and keep up to date the Specification
(Schedule 3) throughout the Contract Period. Any material amendment to
the Specification (Schedule 3) shall be subject to the Contract Change
Procedures and may lead to an adjustment to the Pricing Schedule in
Schedule 7.
.. Subject to requirements of Regulation 72 of the Public Contract
Regulations 2015 and Clause 5 of this Framework Agreement the Department
reserves the right to amend or refine the Specification (Schedule 3)
prior to undertaking each Call-off Contract to incorporate continuous
improvement, lessons learnt from previous cohorts (including the test
and learn Early Roll-Out contracts), and any interdependent factors
relating to the Early Career Framework, including but not limited to:
[arabic]
... the ECF digital project;
... the independent Quality Assurance function;
... other models or provisions of ECF delivery;
... opportunities to increase synergies with interdependent programmes
including, but not limited to, National Professional Qualifications,
Teaching School Hubs, and Initial Teacher Training.

. ORDERING PROCEDURES
[arabic]
.. The Parties shall enter into a Call-Off Contract for a specified
period and Orders for individual pieces of work during the duration of
the Call-Off Contract shall be placed in accordance with the Call-Off
Procedures (Schedule 4). The Contractor shall not accept an Order except
in accordance with the Ordering Procedures.
. CHANGES TO THIS FRAMEWORK AGREEMENT
[arabic]
.. No amendment to the provisions of this Framework Agreement shall be
effective unless it is in writing and signed by each of the Parties.
.. For these purposes a “Change” shall include any amendment to this
Framework Agreement and any material amendments to the Specification
(Schedule 3). For each Change that is agreed by the Department and the
Contractor pursuant to this Clause 5, this Framework Agreement or the
Specification (Schedule 3) shall be amended to the extent necessary to
give effect to that Change. Unless and until such amendment is made in
accordance with this Clause 5, no Change shall be considered effective,
and this Framework Agreement and the Specification (Schedule 3) shall
not in any way be considered to have been varied.
.. In the event that a Change is implemented such Change has an effect
on the Model Call-Off Contract (Schedule 2), the Model Call-Off Contract
shall be amended accordingly.
.. To the extent that a Change affects Call-Off Contracts that the
Parties have already entered into prior to the Change, the Contractor
and the Department shall adhere to the procedure for contract change set
out in the relevant Call-Off Contract.
.. The Department anticipates that changes may be required during the
Contract Period in regards to paragraph 3.5.

. COMMUNICATIONS
[arabic]
.. Except as otherwise expressly provided, no communication from one
Party to the other shall have any validity under this Framework
Agreement unless made in writing by or on behalf of the party sending
such communication.
.. Any notice or other formal communication whatsoever which either the
Department or the Contractor are required or authorised by this
Framework Agreement to give or make to the other shall be made by email,
or via the messaging facility in the Departments nominated contract
management platform, addressed to the other at the address specified in
Clause 6.3.
.. For the purposes of Clause 6.2 the address of each party shall be as
follows
[arabic]
... The Department: ecf.delivery@education.gov.uk
... The Contractor: *[REDACTED]*

. CONTRACT PERIOD, SUSPENSION AND TERMINATION
+
*CONTRACT PERIOD*
[arabic]
.. This Framework Agreement shall commence on the Commencement Date and
shall expire on the Expiry Date unless terminated earlier pursuant to
this Clause 7 (the "Contract Period").
+
*TERMINATION*
.. The Department may at any time by notice in writing terminate this
Framework Agreement as from the date of service of such notice, or a
later date specified in such notice, if:
[arabic]
... there is a change of control, as defined by Section 1124 of the
Corporation Tax Act 2010, in the Contractor or its Parent Company where
the proposed new owner has:
[arabic]
.... been convicted of a criminal offence relating to the conduct of its
business or profession including but not limited to under the Bribery
Act 2010; or
.... committed an act of grave misconduct in the course of its business or
profession; or
.... failed to comply with any obligations relating to the payment of any
taxes or social security contributions; or
.... made any serious misrepresentations in the tendering process for any
project or matter in which the public sector has or had a significant
participation; or
.... failed to obtain any necessary licences or membership of any relevant
body; or
.... the Contractor being an individual, or where the Contractor is a firm,
any partner or partners in that firm who together are able to exercise
direct or indirect control, shall at any time become bankrupt or shall
have a receiving order or administration order made against him or shall
make any composition or arrangement with or for the benefit of his
creditors, or shall make any conveyance or assignment for the benefit of
his creditors, or shall purport so to do, or appears unable to pay or to
have no reasonable prospect of being able to pay a debt within the
meaning of Section 268 of the Insolvency Act 1986, or he shall become
apparently insolvent within the meaning of the Bankruptcy (Scotland) Act
1985 as amended by the Bankruptcy (Scotland) Act 1993, or any
application shall be made under any bankruptcy or insolvency act for the
time being in force for sequestration of his estate, or a trust deed
shall be granted by him on behalf of his creditors, or any similar event
occurs under the law of any other jurisdiction; or
.... the Contractor, being a company, passes a resolution, or the Court makes
an order that the Contractor or its Parent Company be wound up otherwise
than for the purpose of a bona fide reconstruction or amalgamation, or a
receiver, manager or administrator on behalf of a creditor is appointed
in respect of the business or any part thereof of the Contractor or the
Parent Company (or an application for the appointment of an
administrator is made or notice to appoint an administrator is given in
relation to the Contractor or the Parent Company), or a moratorium comes
into force pursuant to Schedule A1 of the Insolvency Act 1986, or
circumstances arise which entitle the Court or a creditor to appoint a
receiver, manager or administrator or which entitle the Court otherwise
than for the purpose of a bona fide reconstruction or amalgamation to
make a winding-up order, or the Contractor or its Parent Company is
unable to pay its debts within the meaning of Section 123 of the
Insolvency Act 1986 or any similar event occurs under the law of any
other jurisdiction; or
.. The circumstances detailed in Clause 9.3.1 or Clause 9.3.2 arise.
.. The Department may at any time by notice in writing terminate this
Framework Agreement immediately if the Contractor is in material default
of any obligation under this Framework Agreement and:
[arabic]
... the material default is capable of remedy and the Contractor shall
have failed to remedy the material default within thirty (30) Days of
written notice to the Contractor specifying the material default and
requiring its remedy; or
... the material default is not capable of remedy.
.. The Contractor shall promptly notify the Department in writing on
each occasion of the occurrence of any of the events specified in Clause
7.2.
.. If any funding, including but not limited to the Early Career
Framework, from governmental or other sources for the provision of the
Services, or for a programme or project to which the provision of the
Services relates is withdrawn, reallocated or no longer available in
such a way that this Framework Agreement cannot reasonably continue the
Department may terminate the Framework Agreement by serving a minimum of
3 months’ written notice on the Contractor.
.. The Department may, in any event, terminate this Framework by serving
a minimum of 6 months’ written notice on the Contractor.
.. The termination of this Framework Agreement shall be without
prejudice to any rights of either party that shall have accrued before
the date of such termination.
.. The termination of this Framework Agreement will not terminate any
Call-Off Contracts that have been awarded under the Framework Agreement
as set out in Clause 8.2.
+
*SUSPENSION*
.. The Department may at any time by notice in writing suspend the
Contractor from this Framework Agreement, such suspension to take effect
as from the date specified in such notice and to take effect until such
time as the material defect has been remedied by the Contractor, to
Department’s satisfaction or the Department terminates this Framework
Agreement in accordance with clause 7.4.
.. The Contractor’s performance of the Services under each Call-Off
Contract it enters into with the Contractor shall be to the standard as
set out in the Call-Off Contract. Where the Contractor’s performance of
the Services under any Call-Off Contract falls below the required
standards, as set out below, the Department may, by notice to the
Contractor in writing, suspend the Contractor from further call-off
opportunities under the Framework Agreement, such suspension to take
effect from the date set out in the notice until such time as the
Contractor’s performance under the requisite Call-Off Contract has been
rectified to the satisfaction of the Department, in accordance with the
terms of the Call-Off Contract, and the Department has notified the
Contractor under this Framework Agreement that the suspension has been
lifted;
[arabic]
... where the Minimum Recruitment Target as set out in the Call-Off
Contract, and as set out at paragraph 26, Table 4 (Minimum delivery
Targets) of Schedule 7 (Pricing and Performance) of this Framework
Agreement, has not been met;
... where remedial action(s) as a consequence of a Service Failure in
line with paragraphs 2.11 to 2.13 of Schedule 2: Part 2 of a Call-off
Contract, has been invoked;
... for any period during which the Contractor is required for remedy an
unresolved QA Failure in accordance with paragraph 3.10 of Schedule 2
Part 2 of any Call-Off Contract.
.. Suspension from this Framework Agreement will not terminate any
Call-Off Contracts that have been awarded under the Framework Agreement
as set out in Clause 8.2.

. CONSEQUENCES OF TERMINATION suspension and EXPIRY
[arabic]
.. Notwithstanding the service of a notice to terminate this Framework
Agreement, the Contractor shall continue to fulfil its obligations under
this Framework Agreement until the date of termination of this Framework
Agreement or such other date as required under this Clause 8.
.. A termination of or suspension from this Framework Agreement shall
not cause any Call-Off Contracts to terminate automatically. For the
avoidance of doubt, all Call-Off Contracts shall remain in force unless
and until they are terminated or expire in accordance with their own
terms.
.. The provisions of Clauses 8, 10, 12, 14, 17 and 21 and without
limitation to the foregoing, any other provision of this Framework
Agreement which by its terms is to be performed or observed
notwithstanding termination or expiry or which is expressed to survive
termination or expiry shall survive the termination or expiry of this
Framework Agreement.
. WARRANTIES AND REPRESENTATIONS
[arabic]
.. The Contractor warrants and represents that:
[arabic]
... it has full capacity and authority and all necessary consents
(including, where its procedures so require, the consent of its Parent
Company) to enter into and to perform this Framework Agreement and that
this Framework Agreement is executed by a duly authorised representative
of the Contractor;
... as at the Commencement Date of this Framework Agreement, all
information contained in its final tender remains true, accurate, and
not misleading save as may have been specifically disclosed in writing
to the Department prior to the execution of this Framework Agreement;
... this Framework Agreement shall be performed in compliance with all
Legislation as amended from time to time;
... it has taken and shall continue to take all steps, in accordance
with Good Industry Practice, to prevent the introduction, creation or
propagation of any disruptive element (including any virus, worm and/or
trojan horse) into systems, data, software or Confidential Information
(held in electronic form) owned by or under the control of, or used by,
the Department;
... on behalf of itself and its Affiliates or Parent Company, in the
three (3) years prior to the Commencement Date of this Framework
Agreement and continuing throughout the Contract Period:
[arabic]
.... it has conducted all financial accounting and reporting activities in
compliance in all material respects with the generally accepted
accounting principles that apply to it in any country where it files
accounts;
.... it has been in full compliance with all applicable securities laws and
regulations in the jurisdiction in which it is established; and
.. it has not performed any act or omission with respect to its
financial accounting or reporting which could have an adverse effect on
the Contractor’s position as an ongoing business concern or its ability
to fulfil its obligations under this Framework Agreement.
.. The Contractor acknowledges that:
[arabic]
... any breach of the warranties in Clause 9.1 (other than a breach of
Clause 9.1.5) shall be remedied as a matter of urgency at no cost to the
Department. Failure to remedy the breach (if capable of remedy) so as to
comply with Clause 9.1 within five (5) Working Days of a notice served
on the Contractor specifying the breach and requiring its remedy by the
Department shall constitute a material breach of this Framework
Agreement entitling the Department to terminate in accordance with
Clause 7.3; and
... a breach of its obligations in Clause 9.1.5 shall afford the
Department the right to immediately terminate this Framework Agreement
without liability or payment of any charges or costs whatsoever.
.. Except as expressly stated in this Framework Agreement, all
warranties and conditions, whether express or implied by statute, common
law or otherwise (including fitness for purpose) are hereby excluded to
the extent permitted by law.
.. The Contractor and the Department each warrant to the other that they
have undertaken all requisite corporate and other action to approve the
entering into and performance of this Framework Agreement.
. LIABILITY
[arabic]
.. Subject to Clauses 10.2, 10.3 and 10.4 the Parties shall be liable to
each other for Direct Losses, whether in respect of breach of contract,
misrepresentation, negligence or otherwise.
.. Nothing in this Framework Agreement shall limit or exclude a party's
liability for:
[arabic]
... death or personal injury caused by its negligence, or the negligence
of its employees, agents or subcontractors;
... fraud or fraudulent misrepresentation; or
... breach of the terms implied by section 2 of the Supply of Goods and
Services Act 1982 (title and quiet possession) or any other liability
which cannot be limited or excluded by applicable law.
.. Neither party to this Framework Agreement shall have any liability to
the other party, whether in contract, tort (including negligence),
breach of statutory duty, or otherwise, for any loss of profit, or for
any indirect or consequential loss arising under or in connection with
this Framework Agreement.
.. For the avoidance of doubt the provisions of Clause 10.3 shall not be
taken as limiting the right of the Department to claim for:
[arabic]
... any additional operational and/or administrative costs and expenses
arising as a direct consequence of a breach;
... any wasted expenditure or charges rendered unnecessary and/or
incurred by the Department arising as a direct consequence of a breach.
.. Each Party’s aggregate liability under Clause 10.1 for the Contract
Period shall be limited to five hundred thousand pounds (£500,000).
. GUARANTEE
[arabic]
.. Not used.
. DATA PROTECTION
[arabic]
.. The Contractor shall comply at all times with the Data Protection
Requirements as set out in the Model Call-Off Contract.
. INTELLECTUAL PROPERTY RIGHTS
[arabic]
.. The Contractor shall comply at all times with the Intellectual
Property Rights as set out in the Model Call-Off Contract.
. CONFIDENTIALITY
[arabic]
.. The Department and the Contractor acknowledge that any Confidential
Information originating from:
[arabic]
... the Department, their servants or agents is the property of the
Department; and
... the Contractor, its employees, servants or agents is the property of
the Contractor.
.. The Contractor and the Department shall procure that:
[arabic]
... any person employed or engaged by them shall only use Confidential
Information for the purposes of this Framework Agreement and shall only
disclose any Confidential Information to any third party with the prior
written consent of the originator of that Confidential Information;
... any person employed or engaged by them in connection with this
Framework Agreement shall not, in the course of such employment or
engagement, disclose any Confidential Information to any third party
without the prior written consent of the originator of that Confidential
Information;
... they shall take all necessary precautions to ensure that all
Confidential Information is treated as confidential and not disclosed
(save as aforesaid) or used other than for the purposes of this
Framework Agreement by their employees, servants, agents or
sub-contractors.
... without prejudice to the generality of the foregoing neither they
nor any person engaged by them whether as a servant or a consultant or
otherwise shall use the Confidential Information for the solicitation of
business from the other or from any third party.
.. The provisions of Clause 14.1 and Clause 14.2 shall not apply to any
information which:
[arabic]
... is or becomes public knowledge other than by breach of this Clause
14; or
... is in the possession of the recipient without restriction in
relation to disclosure before the date of receipt from the disclosing
party; or
... is received from a third party who lawfully acquired it and who is
under no obligation restricting its disclosure; or
... is independently developed without access to the Confidential
Information; or
... must be disclosed pursuant to a statutory, legal or parliamentary
obligation placed upon the party making the disclosure, including any
requirements for disclosure under the Freedom of Information Act 2000 or
the Environmental Information Regulations 2004.
.. Nothing in this Clause 14 shall be deemed or construed to prevent the
Department from disclosing any Confidential Information obtained from
the Contractor:
[arabic]
... to any department, office or agency of Her Majesty’s Government.
... to any consultant, Contractor or other person engaged by the
Department in connection herewith, provided that the Department shall
have required that such information be treated as confidential by such
consultant, Contractor or other person, together with their servants,
including requiring servants to enter into a confidentiality agreement
(to which the Contractor shall also be a party) prior to disclosure of
the Confidential Information whereupon the Department shall have no
further liability for breach of confidentiality in respect of
consultants, contractors or other people; and
.. Nothing in this Clause 14 shall prevent the Contractor or the
Department from using data processing techniques, ideas and know-how
gained during the performance of this Framework Agreement in the
furtherance of its normal business, to the extent that this does not
relate to a disclosure of Confidential Information or an infringement by
the Department or the Contractor of any Intellectual Property Rights.
. PUBLICITY
[arabic]
.. Neither party shall, by itself, its employees or agents (and each
party shall procure that none of its sub-contractors shall) communicate
with representatives of the press, television, internet, radio or other
communications media on any matter concerning this Framework Agreement
save as may be provided for in advance in writing by the parties from
time to time.
. DISPUTE RESOLUTION
[arabic]
.. The Parties shall use all reasonable endeavours to negotiate in good
faith and settle amicably any dispute that arises during the continuance
of this Framework Agreement. This shall include escalating the dispute
to a more senior level within both the Department and the Contractor
with a view to reaching a settlement.
.. Any dispute not capable of resolution by the parties in accordance
with the terms of Clause 16 shall be settled as far as possible by
mediation in accordance with the Centre for Dispute Resolution (CEDR)
Model Mediation Procedure.
.. No party may commence any court proceedings/arbitration in relation
to any dispute arising out of this Framework Agreement until they have
attempted to settle it by mediation, but any such mediation may be
terminated by either party at any time of such party wishing to commence
court proceedings/arbitration.[#_DV_M289 .anchor]##
. RECOVERY OF SUMS DUE
[arabic]
.. If any sum of money shall be due from the Contractor, the same may be
deducted from any sum then due or which at the time thereafter may
become due to the Contractor under any agreement with the
Department
. DISCRIMINATION
[arabic]
.. The Contractor shall not unlawfully discriminate within the meaning
and scope of the provisions of the Equality Act 2010 or any statutory
modification or re-enactment thereof or any other Law relating to
discrimination in employment.
.. The Contractor shall take all reasonable steps to secure the
observance of the provisions of Clause 18.1 by the Sub-Contractors
employed in the execution of this Framework Agreement.
. CORRUPT GIFTS
[arabic]
.. The Contractor shall not offer or give or agree to give any person
acting for and on behalf of the Department any gift or consideration of
any kind as an inducement or reward for doing, forbearing to do, or for
having done or forborne to do any act in relation to the obtaining or
execution of this Framework Agreement.
.. Any breach of Clause 19.1 by the Contractor or by anyone employed by
it or acting on its behalf (whether with or without the knowledge of the
Contractor) or the commission of any offence by the Contractor or by
anyone employed by him or acting on his behalf under the Bribery Act
2010, in relation to this Framework Agreement shall entitle the
Department to terminate this Framework Agreement and recover from the
Contractor the amount of any loss resulting from such termination and/or
to recover from the Contractor the amount or value of any such gift or
consideration.
.. Any dispute, difference or question arising in respect of the
interpretation of this Clause 19, the right of the Department to
terminate this Framework Agreement or the amount or value of any such
gift or consideration shall be decided by the Department, whose decision
shall be final and conclusive.
. TRANSFER AND SUB-CONTRACTING
[arabic]
.. This Framework Agreement is personal to the Contractor. Save in
respect of an assignment in whole to an Affiliate of the Contractor in
the event of a solvent reorganisation, amalgamation or reconstruction of
the Contractor or such Affiliate, the Contractor shall not assign,
novate, sub-contract or otherwise dispose of this Framework Agreement or
any part thereof without the previous consent in writing of the
Department.
. RIGHTS OF THIRD PARTIES
[arabic]
.. This Framework Agreement shall not create any rights, under the
Contracts (Rights of Third Parties) Act 1999 or otherwise, that shall be
enforceable by anyone other than the Department and/or the Contractor.
. AUDIT
[arabic]
.. The Contractor shall document, implement and comply with processes,
and keep or cause to be kept full and accurate Records, such that the
Department (or their statutory auditors or authorised agents) may verify
that the Contractor has complied and is complying with its obligations
under this Framework Agreement.
.. The Contractor shall grant to the Department, any statutory auditors
of the Department and any authorised agents of the Department or of its
statutory auditors, the right of reasonable access to any premises of
the Contractor which are used in connection with the performance of the
Contractor’s responsibilities and obligations under this Framework
Agreement, together with a right to reasonable access to all Records.
.. Further to the provisions of Clause 22.2, the Contractor shall
provide, or procure the provision of, all reasonable assistance at all
times for the purposes of carrying out an audit of the Contractor’s
compliance with this Framework Agreement as well as an audit of all
activities, performance, security and integrity in connection therewith.
.. Without prejudice to the foregoing, in the event of an investigation
into suspected fraudulent activity or other serious impropriety by the
Contractor, the Department reserves for itself or any statutory auditor
of the Department the right of immediate access to the premises and
documents described in Clauses 22.1, 22.2 and 22.3 and the Contractor
agrees to render all necessary assistance to the conduct of such
investigation.
.. The Department shall use all reasonable endeavours to ensure that its
auditors cause the minimum amount of disruption to the business of the
Contractor, and shall comply with the building regulations and security
requirements of the Contractor while on the Contractor’s premises.
.. The Contractor shall comply with the provisions of Schedule 10
(Financial Reports and Audit Rights) in regard to financial
transparency, open book costing and audit rights.
. FREEDOM OF INFORMATION
[arabic]
.. The Contractor acknowledges that the Department is subject to the
requirements of FOIA and the Environmental Information Regulations and
shall assist and cooperate with the Department to enable the Department
to comply with its Information disclosure obligations.
.. The Contractor shall and shall procure that its Sub-Contractors
shall:
[arabic]
... transfer to the Department all Requests for Information that it
receives as soon as practicable and in any event within two (2) Working
Days of receiving a Request for Information;
... provide the Department with a copy of all Information in its
possession, or power in the form that the Department require within five
(5) Working Days (or such other period as the Department may specify) of
the Department’s request; and
... provide all necessary assistance as reasonably requested by the
Department to enable the Department to respond to the Request for
Information within the time for compliance set out in section 10 of the
FOIA or regulation 5 of the Environmental Information Regulations.
.. The Department shall be responsible for determining in its absolute
discretion whether any Information is exempt from disclosure in
accordance with the provisions of FOIA or the Environmental Information
Regulations.
.. In no event shall the Contractor respond directly to a Request for
Information unless expressly authorised to do so by the Department.
.. The Contractor acknowledges that the Department may, acting in
accordance with the Department of Constitutional Affairs’ Code of
Practice on the Discharge of the Functions of Public Authorities under
Part 1 of the Freedom of Information Act 2000, be obliged to disclose
Information without consulting or obtaining consent from the Contractor,
or despite having taken the Contractor’s views into account.
.. The Contractor shall ensure that all Information is retained for
disclosure and shall permit the Department to inspect such records as
requested from time to time.[#_DV_M353 .anchor]##
. PERFORMANCE MANAGEMENT
[arabic]
.. The Department will monitor the Contractor’s performance under the
Framework Agreement and reserves the right to require the Contractor to
provide any information and / or to assist it in doing so and / or to
meet with the Department to discuss performance under the Framework
Agreement. The information / data requested may include but not be
limited to performance information that relates to one or more Call-Off
Contracts awarded under the Framework Agreement.
.. The performance measures that relate to the provision of the Services
shall be as set out in the Call-Off Contract.
.. In addition to the performance management requirements set out for
each individual Call-Off Contract, the Contractor shall attend and
proactively participate in any joint collaborative meetings that the
Department convenes under the Framework Agreement. These meetings will
cover, but not be limited to emerging challenges, joint solutions,
recruitment, sharing best practice and lessons learnt, exploring
opportunities for efficiency/resource improvements, and identifying
future opportunities to work more collaboratively with the Department
and/or other Framework Agreement Providers.
. STATUTORY INVALIDITY
[arabic]
.. The Department and the Contractor expressly agree that should any
limitation or provision contained in this Framework Agreement including
the Model Call-Off Contract be held to be invalid under any particular
statute or law, or any rule, regulation or bye-law having the force of
law, it shall to that extent be deemed to be omitted but, if the
Department or the Contractor thereby become liable for loss or damage
which would have otherwise been excluded, such liability shall be
subject to the other limitations and provisions set out in this
Framework Agreement.
. FRAUD and IRREGULARITY
[arabic]
.. The Contractor shall notify the Department immediately where it
becomes aware of any instance of suspected fraud or financial
irregularity in the delivery of the Services including but not limited
to cases of:
[arabic]
... Collusion with employees of the Department;
... Computer fraud;
... The submission to the Department of inaccurate, incomplete,
misleading or falsified information for the purpose of making a Charge
to the Department;
... Fraud involving sub-contractors and/or Participants;
... Any noncompliance with the requirements of the Call-Off Contract,
Schedule 2: Part 1 (Pricing) in relation to the claiming, receipt of and
administration of the Charges,
+
Provided nothing in this clause 26 shall require the Contractor to do
anything which may cause it to infringe the any law.
.. Where the Department has reasonable cause to believe that any fraud
or irregularity has occurred in relation to the delivery of the Services
under a Call-Off Contract and/or the payment of the Charges and/or the
flow down of payment to the supply chain by the Department under a
Call-Off Contract the Department shall have the right of access to the
Contractor’s premises at any reasonable time with or without notice to
examine and remove or copy all relevant documents and records including
electronic records and to interview the Contractor.
.. The Department reserves the right to recover from the Contractor any
Charges paid where the payment of the Charges or any arrangement between
the Contractor and a sub-contractor or Participant breaches the terms of
the Framework Agreement or the provisions of Schedule 2 Part 2 (Pricing)
of the Call-Off Contract and/or was based on wrong, inaccurate or
misleading information.
. SEVERABILITY
[arabic]
.. Subject to the provisions of Clause 25 (Statutory Invalidity), if any
provision of this Framework Agreement is held invalid, illegal or
unenforceable for any reason, such provision shall be severed and the
remainder of the provisions hereof shall continue in full force and
effect as if this Framework Agreement had been executed with the invalid
provision eliminated. In the event of a holding of invalidity so
fundamental as to prevent the accomplishment of the purpose of this
Framework Agreement, the Department and the Contractor shall immediately
commence good faith negotiations to remedy such invalidity.
. WAIVER
[arabic]
.. The failure of the Contractor or the Department to insist upon strict
performance of any provision of this Framework Agreement or to exercise
any right or remedy to which it is entitled under this Framework
Agreement, shall not constitute a waiver thereof and shall not cause a
diminution of the obligations established by this Framework Agreement.
.. A waiver of any default shall not constitute a waiver of any other
default.
.. No waiver of any of the provisions of this Framework Agreement shall
be effective unless it is expressed to be a waiver communicated by
notice, in accordance with the provisions of Clause 6 (Communications).
. NON-EXCLUSIVITY and CONTRACTOR status
[arabic]
.. This Framework Agreement is non-exclusive and the Department shall:
[arabic]
... at all times be entitled to enter into contracts for services that
are similar to or the same as the Services as set out in Schedule 3 with
suppliers other than the Contractors who have been appointed to the
Framework Agreement;
... at all times be entitled to procure contracts and / or framework
agreements for services that are similar to or the same as the Services
as set out in Schedule 3 to operate in parallel with or to replace the
Framework Agreement;
... not be deemed to make or have made any representation or warranty to
the Contractor with regards to this Framework Agreement being anything
other than non-exclusive.
.. No guarantee or representation shall be deemed to have been made by
the Department in respect of the total quantities or values of the
Services to be ordered under this Framework Agreement. Further, the
Contractor acknowledges and agrees that it has not entered into this
Framework Agreement on the basis of any such guarantee or
representation.
.. In carrying out its obligations under the Framework Agreement and
Orders placed under it the Contractor agrees that it will be acting as
principal and not as the agent of the Department.
.. In the event of a Financial Distress Event, the provisions in
Schedule 8 (Financial Distress) shall apply.
. LAW AND JURISDICTION
[arabic]
.. The Department and the Contractor accept the exclusive jurisdiction
of the English courts and agree that this Framework Agreement is to be
governed by and construed according to English law.
. ENTIRE AGREEMENT
[arabic]
.. This Framework Agreement constitutes the entire understanding between
the Department and the Contractor relating to the subject matter.
.. Neither the Department nor the Contractor have relied upon any
representation or promise except as expressly set out in this Framework
Agreement.
.. Both the Department and the Contractor unconditionally waive any
rights they may have to claim damages against the other on the basis of
any statement made by the other (whether made carelessly or not) not set
out or referred to in this Framework Agreement (or for breach of any
warranty given by the other not so set out or referred to) unless such
statement or warranty was made or given fraudulently.
.. Both the Department and the Contractor unconditionally waive any
rights they may have to seek to rescind this Framework Agreement on the
basis of any statement made by the other (whether made carelessly or
not) whether or not such statement is set out or referred to in this
Framework Agreement unless such statement was made fraudulently.

*AS WITNESS* the hands of the parties:

[width="100%",cols="34%,66%",options="header",]
|===
|Authorised to sign for and on behalf of [REDACTED] |
|Signature: |

|Name in CAPITALS: |

|Position in Organisation: |

|Address in full: |

|Date: |

|Authorised to sign for and on behalf of the Secretary of State for
Education |

|Signature: |

|Name in CAPITALS: |

|Position in Organisation: |

|Address in full: |

|Date: |
|===

*SCHEDULE 1 -* *DEFINITIONS*

[width="100%",cols="29%,71%",]
|===
|Additional Clauses |means the Clauses set out in Schedule 3 (Additional
Clauses) of the Model Call-Off Contract;

|Affiliate |in relation to any person, the holding company or subsidiary
of that person or any subsidiary of such holding company, and “holding
company” and “subsidiary” shall have the meaning given to them in
Section 1159 and Schedule 6 of the Companies Act 2006;

|Appropriate Body |has the meaning given in the Education (Induction
Arrangements for School Teachers) (England) Regulations 2012 and refers
to a body with responsibility under those regulations for certifying
that an Early Career Teacher has successfully completed their induction
period;

|Call-Off Contract |The Model Call-Off Contract set out in Schedule 2;

|Central Government Body a|
means a body listed in one of the following sub-categories of the
central Government classification of the Public Sector Classification
Guide, as published and amended from time to time by the Office of
National Statistics;

[loweralpha]
. Government Department;
. Non-Departmental Public Body or Assembly Sponsored Public Body (advisory, executive, or tribunal);
. Non-ministerial Department; or
. Executive Agency;

|Change |any change as set out in Clause 5.2 (Changes to this Framework
Agreement);

|Charges |means the charges payable by the Department for the
performance of the Ordered Services by the Contractor as set out in the
Order and payable in accordance with the Model Call-Off Contract;

|Commencement Date |means 01 March 2021 or such other date agreed in
writing by the Parties;

|Confidential Information |means any information, however it is
conveyed, that relates to the business, affairs, developments, trade
secrets, know-how, personnel and contractor s of either party, including
Intellectual Property Rights, together with all information derived from
the above, and any other information clearly designated as being
confidential (whether or not it is marked as “confidential”) or which
ought reasonably to be considered to be confidential;

|Contract Change Notice (CCN) |means a Contract Change Notice in the
form set out at the Annex 1 to Schedule 5 (Contract Change Procedure);

|Contract Change Procedures |means the procedures specified in Schedule
5 (Contract Change Procedure) for making changes to this Framework
Agreement;

|Contract Period |means the term of this Framework Agreement as set out
in Clause 0, unless terminated earlier in accordance with the provisions
of Clauses 7.2 or 7.4;

|Crown Body |means any department, office or agency of the Crown;

|Department |means the Secretary of State for Education, of Sanctuary
Buildings, 20 Great Smith Street, London, SW1P 3BT;

|Direct Losses |means all damage, losses, indebtedness, claims, actions,
cash, expenses (including the cost of legal or professional services,
legal costs being an agent/client, client paying basis), loss of use,
proceedings, demands and charges whether arising under statute, contract
or at common law but to avoid doubt, excluding Indirect Losses;

|Dispute |any difference or dispute between the Department and the
Contractor arising out of or in connection with this Framework Agreement
(including any question as to the validity or interpretation of this
Framework Agreement and including any dispute arising before or after
termination of this Framework Agreement);

|Environmental Information Regulations |mean the Environmental
Information Regulations 2004 and any guidance and/or codes of practice
issued by the Information Commissioner or relevant Government Department
in relation to such regulations;

|European Economic Area |from time to time the European Economic Area as
created by The Agreement on the European Economic Area 1992 or any
successor or replacement body, association, entity or organisation which
has assumed either or both the function and responsibilities of the
European Economic Area;

|Expiry Date |means 28 February 2025 or such other date agreed in
writing by the Parties;

|Financial Distress Event |the occurrence of one or more of the events
listed in Paragraph 3.1 of Schedule 8 (Financial Distress)

|Framework Agreement |means this Framework Agreement, comprised of the
Clauses and Schedules;

|Framework Manager |means a representative of either party responsible
for ensuring the parties are performing their obligations under this
Framework Agreement, until notified otherwise in writing the
Department’s Framework Manager shall be [REDACTED] ([REDACTED]);

a|
FOIA

GDPR

a|
means the Freedom of Information Act 2000 and any subordinate
legislation made under this Act from time to time together with any
guidance and/or codes of practice issued by the Information Commissioner
or relevant Government Department in relation to such legislation;

Means the General Data Protection Regulation (Regulation (EU) 2016/679)

|Good Industry Practice |that degree of skill, care, prudence, foresight
and operating practice which would reasonably and ordinarily be expected
from time to time of a skilled and experienced operator (engaged in the
same type of undertaking as that of the Contractor) or any
Sub-Contractor under the same or similar circumstances;

|Guarantee |an agreement in the form set out at Schedule 9 entered into
in accordance with Clause 11;

|Guarantor |the party identified as such in the Guarantee;

|Her Majesty’s Government |means the duly elected Government for the
time being during the reign of Her Majesty and/or any department,
committee, office, servant or officer of such Government;

|Indirect Losses |means loss of profits, loss of production, loss of
business, loss of business opportunity, or any claim for consequential
loss or for indirect loss of any nature;

|Information |has the meaning given under section 84 of the Freedom of
Information Act 2000;

|Intellectual Property Rights |means any copyright, rights in designs,
database rights, domain names, trademarks, service marks, patents or any
applications for any of the foregoing, know-how or similar rights or
obligations (whether registerable or not) including Moral Rights as
defined in Chapter IV of the Copyright, Designs and Patents Act 1988;

|LED |means Law Enforcement Directive (Directive (EU) 2016/680)

|Legislation |means any applicable law, statute, bye-law, regulation,
order, regulatory policy, guidance or industry code, rule of court or
directives or requirements of any Regulatory Body, delegated or
subordinate legislation or notice of any Regulatory Body;

|Model Call-Off Contract |means the model Call-Off Contracts in Schedule
2 which specify the terms and conditions for Call-Off Contracts (as such
may be amended from time to time);

|Order |means an order for Services served by the Department on the
Contractor in accordance with the Ordering Procedures;

|Ordered Services |means any Services available under this Framework
Agreement the Department has instructed the Contractor to carry out
under the terms of a Call-Off Contract by means of a valid Order placed
in accordance with the Ordering Procedures;

|Ordering Procedures |means the ordering procedures specified in Clause
4 of this Framework Agreement;

|Protective Measures |Means appropriate technical and organisational
measures which may include, pseudonymising and encrypting Personal Data,
ensuring confidentiality, integrity, availability and resilience of
systems and services, ensuring that availability of and access to
personal Data can be restored in a timely manner after an incident , and
regularly assessing an evaluating the effectiveness of the such measures
adopted by it;

|Qualifying Change in Law a|
means:-

[loweralpha]
. any Change in Law which specifically refers to the provision of a
service the same as or similar to the Services; or
. a Change in Law the terms of which apply expressly to the Project and
to similar projects and/or the Contractor and not to other persons;

which was not foreseeable at the Commencement Date;

|Records |means such full and accurate records as are required to be
kept by the Contractor to satisfy the requirements of Clause 22 (Audit);

|Regulatory Bodies |means those Government departments and regulatory,
statutory and other entities, committees and bodies which, whether under
statute, rules, regulations, codes of practice or otherwise, are
entitled to regulate, investigate, or influence the matters dealt with
in this Framework Agreement or any other affairs of the Department and
“Regulatory Body” shall be construed accordingly;

|Requests for Information |means a request for information or an
apparent request under the Code of Practice on Access to Government
Information, FOIA or the Environmental Information Regulations;

|Services |means the services specified in Schedule 3 (the
Specification) that the Contractor shall make available to the
Department in accordance with this Framework Agreement;

|SME |Means a micro, small or medium-sized enterprise defined in
accordance with the European Commission Recommendation 2003/361/EC and
any subsequent revisions;

|Specification |means the specification of Services being offered to the
Department by the Contractor under this Framework Agreement as included
in this Framework Agreement at Schedule 3;

|Sub-Contractor |means any contractor selected, appointed and managed by
the Contractor. The terms “Sub-Contract” and “Sub-Contracting” shall be
similarly construed;

|Termination Date |shall mean the date on which the Project Agreement
terminates before the end of its intended contract period, in accordance
with the terms of the Project Agreement.

|TUPE |means the Transfer of Undertakings (Protection of Employment)
Regulations 2006 (246/2006) and or any other regulations enacted for the
purpose of implementing the EC Acquired Rights Directive 77/187 into
English law;

|Working Day |means any day other than a Saturday or Sunday or public
holiday in England and Wales;
|===

== SCHEDULE 2 – MODEL CALL-OFF CONTRACT

The Model Call-Off Contract is attached as a separate Schedule to this
Framework Agreement.

== SCHEDULE 3 – SERVICE SPECIFICATION

=== SECTION 1: BACKGROUND

. Context
[arabic]
.. Teachers are the foundation of the education system – there are no
great schools without great teachers. At the heart of great teaching and
great school leadership is a shared, evidence-informed understanding of
what works.

.. Delivering on the commitments set out in the
https://www.gov.uk/government/publications/teacher-recruitment-and-retention-strategy[[.underline]#Teacher
Recruitment and Retention Strategy#], the DfE is in the process of
transforming training and support for teachers at all stages of their
career.

.. The DfE has revised the Initial Teacher Training Core Content
Framework and, through the implementation of the Early Career Framework
(“ECF”), will support teachers in the first years of their career with a
structured and high quality two-year induction.

.. Building from this, a priority of the DfE is to help all teachers
and leaders continuously develop their knowledge and skills throughout
their careers, so that every child in the classroom in every school gets
a world-class start in life.

.. National Professional Qualifications (NPQs) provide training and
support for teachers and leaders at all levels. As set out in the
Teacher Recruitment and Retention Strategy, the DfE has committed to
developing three new specialist NPQs. Alongside this the DfE is
reviewing the suite of leadership NPQs. 

.. It is the DfE’s intention that the revised suite of NPQs will
complete the golden thread from initial teacher training through to
school leadership, rooting teacher and leader development in the best
available evidence and collective wisdom of the profession.

. Introduction
[arabic]
.. The Contractor is required to deliver the Full Induction Programme
to support the National Roll-Out of the ECF reforms.

.. National Roll-Out of the ECF reforms aims to improve the quality and
support of early career teachers (“ECTs") through an entitlement of two
years of professional development. Contractors will do this by providing
schools with access to materials and training programmes underpinned by
the ECF, to support them to offer an ECF-based induction to their
ECTs and support them with trained Mentors.  

.. The Contractor is required to understand the context of the ECF,
which is the basis for the Services, and contains the drivers for this
requirement, including (which may be updated as required): 

* The ECF, which underpins an entitlement to a funded, two-year package
of structured training and support for ECTs and their Mentors, available
at:
+
https://www.gov.uk/government/publications/supporting-early-career-teachers[[.underline]#https://www.gov.uk/government/publications/supporting-early-career-teachers#]

* The Core Induction Programmes include high-quality development
materials, underpinned by the ECF, which will support early career
teachers to develop the essential knowledge and skills to set them up
for a successful and fulfilling career in teaching, available at:
+
https://www.early-career-framework.education.gov.uk/[[.underline]#https://www.early-career-framework.education.gov.uk/#]

* The Strengthening Qualified Teacher Status and improving career
progression for teachers, consultation.  The summary of responses
received, along with the Government’s response outlining the next steps,
available at: 
+
https://www.gov.uk/government/consultations/strengthening-qualified-teacher-status-and-career-progression[[.underline]#https://www.gov.uk/government/consultations/strengthening-qualified-teacher-status-and-career-progression#]  

* The DfE’s Teacher Recruitment and Retention Strategy, available at: 
+
https://www.gov.uk/government/publications/teacher-recruitment-and-retention-strategy[[.underline]#https://www.gov.uk/government/publications/teacher-recruitment-and-retention-strategy#]  

* The DfE’s Induction for newly qualified teachers (England) Statutory
guidance for appropriate bodies, headteachers, school staff and
governing bodies, available at:  
+
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/696428/Statutory_Induction_Guidance_2018.pdf[[.underline]#https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/696428/Statutory_Induction_Guidance_2018.pdf#]

* The National Standards for school-based initial teacher training
mentors, available at:  
+
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/536891/Mentor_standards_report_Final.pdf[[.underline]#https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/536891/Mentor_standards_report_Final.pdf#] 

* The Teachers’ Professional Development Standard, defining good
professional development for teachers, available at: 
+
https://www.gov.uk/government/publications/standard-for-teachers-professional-development[[.underline]#https://www.gov.uk/government/publications/standard-for-teachers-professional-development#] 

. Policy background
[arabic]
.. Improving support for ECTs is at the heart of the DfE’s Teacher
Recruitment and Retention Strategy.* 

.. It is essential that ECTs are able to develop the knowledge,
practices and working habits that will set them up for a fulfilling and
successful career in teaching. At the heart of the DfE’s
https://www.gov.uk/government/publications/teacher-recruitment-and-retention-strategy[[.underline]#Teacher
Recruitment and Retention Strategy #]is a commitment to transform
support for teachers at the start of their career. 

.. Statutory induction is a key step in a teacher’s journey towards a
successful career in teaching and is required to support the ECT in
demonstrating that they have met the Teachers’ Standards. All
organisations that offer statutory induction to ECTs must comply with
the same Statutory requirements.  

.. In January 2019, the DfE published the ECF, which sets out what
all ECTs will learn about and learn how to do as part of their
strengthened statutory induction. It is based on expert guidance and the
best available evidence. The Education Endowment Foundation (EEF) has
independently reviewed the framework. 

.. *From September 2021, all teachers undergoing statutory induction
will have a two-year induction underpinned by the ECF.* From September
2021, statutory induction will be extended from one year to two years
and ECTs will be entitled to an ‘ECF based Induction’. The package of
reforms funded by the DfE will ensure new teachers have dedicated time
set aside to focus on their development. By the time the new system is
fully in place, the DfE anticipates investing up to an additional £130
million every year in ECF induction.  

.. An ECF induction entitles ECTs to two years of support, including:
[arabic]
... Funded time away from the classroom (10% in year 1 as now and an
additional 5% off timetable in year 2) to undertake a planned 131-hour
curriculum of training, covering all of the ECF ‘learn that’ and ‘learn
how to’ statements, including:
[lowerroman]
.... Self-directed study sessions (at least 23 hours).
.... Mentor sessions (~ 59 hours).
.... Training sessions (at least 30 hours).

... A trained Mentor, familiar with the evidence and practice of ECF,
with additional funded time away from the classroom to support the ECT
in the second year.

.. *The DfE will make available optional support to help schools
deliver statutory induction.* 

.. The DfE is committed to providing support for schools to implement
the new induction requirements and to minimise the burden on them. This
support includes: 
[arabic]
... *High quality, freely available training materials* for schools to
use to develop and deliver their own induction programmes for their
ECTs. These materials translate the content of the ECF into a structured
induction programme with supporting materials that cover each statement
in the ECF. This was a commitment the DfE made in response to the
consultation on extending induction. For the purposes of the Framework
Agreement, this is called the ‘Core Induction Programme’. These
materials have been published
http://www.early-career-framework.education.gov.uk/[here]footnote:[From
September 2021 the CIP materials will be hosted on the DfE digital
platform.].

... *Funded training programmes for ECTs.* A quality assured training
Contractor will offer schools additional and high quality training and
materials to support the ECT. This will include delivering support
directly to ECTs. The DfE wants to encourage as many schools as possible
to benefit from funded training programmes. In order to ensure all ECTs
are experiencing a consistently high-quality induction
experience, training programmes will be based on the high-quality
training outlines set out in the Core Induction
Programme (see Section 3).   

... *Funded Mentor Training*. The DfE recognises the fundamental
importance of mentoring for ECTs and to the successful delivery of the
ECF. As such, the DfE committed in the consultation response to ensure
that schools have access to high quality training for their Mentors.
This Mentor training will be related to the ECF, funded, and delivered
by a quality assured training Contractor alongside the ECT training.  

.. Given the importance of a Mentor for a successful induction, the DfE
will offer the Mentor training and ECT training as a ‘bundle’ to ensure
that ECTs on the training programmes are supported by a Mentor familiar
not only in mentoring techniques, but also with the ECF itself. Schools
will be offered a Mentor training place for every ECT they sign up.
Though some Mentors support multiple ECTs, the DfE will still offer
schools a Mentor training space for each ECT, to allow schools to build
up mentoring capacity if they wish to.

.. From September 2021, all schools offering statutory induction,
including academies and free schools who may choose to offer it, will be
required to ensure all ECTs receive their entitlement to a two-year
programme of support and development underpinned by the ECF. The ECF
will form the basis of all statutory induction programmes: 
[arabic]
... All ECTs on a statutory induction will have an entitlement to
training across the full range of the ECF – see Section 3 for
further details. 

... Appropriate Bodies will be expected to quality assure the
statutory induction process, including implementation of the ECF. 

.. The DfE will be publishing updated statutory induction guidance in
September 2021 to provide further information on the role of the ECF in
the delivery of a strengthened induction. Schools are free to use the
ECF before this statutory guidance is in place.

.. Formal assessment under the new arrangements will remain the sole
responsibility of the school, with assessment against the Teachers’
Standards and not the ECF. The ECF is not, and should not be used, as an
assessment framework. ECTs will not be expected to collect evidence
against the ECF, and they will continue to be assessed against the
Teachers’ Standards only. The ECF will underpin an entitlement to
training and support for ECTs and should not be seen as an additional
assessment tool.  

.. *To prepare for National Roll-Out in 2021, the DfE is conducting
Early Roll-Out in four areas from September 2020. * 

.. In 2019, the DfE undertook a procurement for Early Roll-Out of the
ECF in (i) the North East, (ii) Greater Manchester,
(iii) Bradford and (iv) Doncaster to deliver a 2 year ‘test and learn’
cohort from September 2020. These areas represent a diverse range of
schools in varying circumstances, which will help to build our
understanding of how to support schools in implementing a programme of
support and development underpinned by the ECF. The Early Roll-Out
cohort is currently supporting over 1,900 ECTs and their assigned
Mentors.

.. Covid-19 has meant that virtually all ECTs starting in September
2020 have had their Initial Teacher Training year curtailed. Therefore,
the DfE extended the availability of high quality support beyond Early
Roll-Out areas and are currently supporting over 4,600 ECTs and their
assigned mentors from across the country, with a one year version of the
Early Roll-Out programme, focusing on schools serving disadvantaged
communities.

.. As part of Early Roll-Out, Contractors were asked to sequence the
ECF into a curriculum, and design self-study materials for ECTs, as well
as training session outlines for ECTs and Mentors. Together these
materials form the Core Induction Programme. National Roll-Out will
consist of training based on these programmes.

.. The National Roll-Out of full training programmes fulfils the next
stage in this process – the requirements of which are set out in this
Specification.  

. Teaching School Hubs
[arabic]
.. In the DfE’s Recruitment and Retention Strategy, the DfE committed
to improving support for all teachers, ensuring that they receive high
quality training and development at every stage of their career – from
Initial Teacher Training through to leadership qualifications. At the
heart of this new system will be Teaching School Hubs (TSH). TSH will
have a concentrated focus on teacher training and development that will
see a return to the original vision behind teaching schools, recognising
teacher and leader development as the most important form of school
improvement.

.. TSH will be expected to play a significant role in delivering the
ECF, and to seek to be involved in the delivery of new Specialist NPQs
and Leadership NPQs. They will also deliver school-based initial teacher
training, and quality assure statutory induction through an Appropriate
Body role. Their clearly defined role in professional development will
make it easier for schools and teachers to identify what opportunities
and support are available to them. TSH will also be able to deliver
other high-quality evidence based CPD that focusses on developing
quality teaching across the hub area.

. Alternative ECF Provision

.. The Teacher Recruitment and Retention Strategy outlined our
commitment to improving training opportunities at every stage of the
teacher career journey. We need a strong delivery infrastructure to
provide a world-class development offer for teachers and leaders. To
support this, the DfE may in the future establish new teacher training
models to deliver the ECF and/or other teacher development programmes.

.. Therefore, the DfE reserves the right to run a separate procurement
during the term of the ECF Framework to establish alternative delivery
models that include the delivery of NRO services and incorporate them
within existing ECF funding and demand.

.. In this event, the DfE will provide further details regarding
opportunities and/or impacts for ECF Framework Providers. ECF Framework
Providers are reminded that under the Framework Agreement there is no
guarantee of there being a specified level of call-offs or indeed any
call-offs at all. There is also no exclusivity in relation to the same
or similar services only being delivered by ECF Framework Providers.

. Appropriate Bodies

.. Organisations, which are also an Appropriate Body, are permitted to
deliver Services for ECF National Roll-Out. This means a Contractor can
deliver training to another school for which that Contractor is also the
Appropriate Body. Similarly, the Contractor does not need to restrict
any delivery partner from both acting as an Appropriate Body to another
school and also delivering training to the same school.

.. The DfE advises that Appropriate Body and training provider roles
are distinct. Note that:

... Appropriate Bodies are responsible for ensuring that schools
provide adequate support for their NQTs, and that their assessment is
fair and consistent across all institutions. Roles and responsibilities
are set out in statutory guidance and include: ensuring that
headteachers/principals are aware of, and capable of meeting their
responsibilities for monitoring support and assessment; and the
monitoring, support, assessment and guidance procedures in place are
fair and consistent.

... Providers should deliver training to Early Career Teachers, as
laid out in the National Roll-Out specification. Separate mechanisms are
in place to quality assure the delivery of training.

=== SECTION 2: SPECIFICATION OF REQUIREMENTS

[arabic, start=7]
. Context
[arabic]
.. Using existing published Core Induction Programme products the
Contractor is required to design and deliver ECT and Mentor Training
Programmes to support the National Roll-Out of the ECF reforms.

.. The ECF sets out what all ECTs will learn about and be trained in as
part of their new strengthened statutory induction period to be
introduced nationally from September 2021.

.. The DfE wishes to provide support for schools to implement the new
induction requirements and to minimise any associated burdens on them.
In Early Roll-Out, 4 Contractors have produced a Full Induction
Programme, made up of six products, designed to support ECTs and their
Mentors. Products 1-4 make up the Core Induction Programme. The Core
Induction Programmes have been published
http://www.early-career-framework.education.gov.uk/[[.underline]#here#]footnote:[From
September 2021 the CIP materials will be hosted on the DfE digital
platform.]. Products 1-6 make up the Full Induction Programme.

.. The Full Induction Programme includes 6 elements:
[arabic]
... Product 1 - Sequence
... Product 2 - Self-directed Study Materials
... Product 3 - Mentor Session Materials
... Product 4 - ECT Training Session Outlines
... Product 5 - ECT Training Programmes
... Product 6 - Mentor Training Programmes

.. In National Roll-Out, the Contractor shall design training for ECTs
and their Mentors (Products 5 and 6) using one of the Core Induction
Programmes produced by our Early Roll-Out Contractors. Contractors must
maintain any defined training models or concepts established in the
chosen Core Induction Programme within their Products 5 and 6.

.. The Contractor will host their selected Core Induction Programme
(Products 1 – 4) and their Products 5 and 6 on a digital platform for
participants undertaking the Full Induction Programme.

.. In designing the training referred to in 7.5, Contractors are
granted flexibility around ‘how’ to deliver the training but not ‘what’
training to deliver. Training session outlines dictate the ECF
statements that Contractors should cover in particular sessions and the
desired outcomes that Contractors shall ensure are met. There is
flexibility on how Contractors achieve those outcomes although the
Contractor is required to adhere to the suggested timings in the
training session outlines. There are no training session outlines for
Mentor training and no specific timings other than Contractors shall
ensure that Mentor training provides for a maximum of 36 hours of
training for Mentors over two years. Mentor training shall as a minimum
ensure Mentors are proficient in the content of the ECF and are equipped
with the core mentoring skills sufficient to support the ECF with the
chosen Core Induction Programme.

.. A brief summary of each of the elements the Contractor must design
in National Roll-Out can be found in *Table 1* below. *Table 2*
describes Products 1-4, as procured in Early Roll-Out, on which the
National Roll-Out Contractors’ training must be based.

.. *Table 1: Description of Products and Services for National Roll
Out*
+
[width="100%",cols="22%,26%,20%,32%",options="header",]
|===
|*Product / Service* |*Overview* |*Product /Service Audience* |*Product
/ Service Purpose*
|5a. ECT Training Programme Content |The Contractor is required to
prepare the content of the ECT Training Programme, based on the Training
Session Outlines to deliver the stated Product/Service Purpose. .2+|ECT .2+a|
ECTs develop a deep understanding of all parts of the ECF, and the
quality of their teaching is improved.

ECTs build effective support networks, including outside of their
school.

|5b. ECT Training Programme Delivery |The Contractor is required to
deliver the ECT Training Programme to ECTs to achieve the
Product/Service Purpose. The delivery mechanism is not prescribed and
may include face-to-face or online. The Contractor shall ensure that the
training programme enables ECTs to build effective support networks.

|6a. Mentor Training Programme Content |The Contractor is required to
design the content of the Training Programme for the Mentors of ECTs to
deliver the stated Product/Service Purpose. The content shall be focused
on the ECF and mentoring knowledge and skills needed for the relevant
Core Induction Programme’s Mentor Sessions. .2+|Mentor .2+a|
Mentors develop a deep understanding of all parts of the ECF in order to
support the ECTs with their understanding of the ECF.

Mentors are able to effectively mentor and tailor their support to the
individual ECT’s needs and experiences.

Mentors have a professional community of support to share best practice.

|6b. Mentor Training Programme Delivery |The Contractor is required to
deliver the Training Programme for the Mentors of ECTs to achieve the
stated Product/Service Purpose. The Training Programme shall be focused
on the ECF and mentoring knowledge and skills needed for the Mentor
sessions. The training programme shall also enable Mentors to build
professional communities of support.
|===

.. *Table 2: Description of the elements of the Core Induction
Programme*
+
[width="100%",cols="22%,26%,20%,32%",options="header",]
|===
|*Product / Service* |*Overview* |*Product /Service Audience* |*Product
/ Service Purpose*
|1. Sequence |Each ‘learn that’ and ‘learn how to’ section of the ECF is
in an order (a “sequence”) across a two-year induction period. This
sequence describes the way ECTs study each section (self-directed /
Mentor sessions / training) and the time to be spent on it. |School and
ECT and Mentor a|
Schools/users/the Contractor are able to deliver a two-year induction
programme that covers each ‘learn that’ and ‘learn how to’ statement in
the ECF.

The sequence enables ECTs to master foundational concepts and knowledge
before moving on to new concepts and knowledge.

Schools, ECTs and Mentors know what to expect in terms of their schedule
and priorities for induction.

|2. Self-directed Study Materials |Materials which support independent
study undertaken by the ECT on specific sections of the ECF as set out
in the Sequence. |ECT a|
ECTs are able to use self-directed study materials to work independently
and at their own pace.

ECTs develop a deep understanding of all parts of the ECF, and the
quality of their teaching is improved.

|3. Mentor Session Materials |Materials which support regular mentoring
sessions between the ECT and their Mentor on specific sections of the
ECF as set out in the Sequence. |ECT and Mentor a|
Schools/the Contractor are able to create provision of Materials that
enables Mentors to prepare effective mentoring sessions quickly.

ECTs receive support from their Mentor to understand and apply the ECF,
which is tailored to the ECT’s individual needs and experiences.

Through discussions with their Mentor, ECTs develop a deep understanding
of all parts of the ECF, and the quality of their teaching is improved.

|4. ECT Training Session Outlines |An outline of content to be covered
within ECT training sessions on specific sections of the ECF as set out
in the Sequence. |School/the Contractor a|
Schools/the Contractor wishing to deliver training themselves (in
National Roll-Out) are able to:

[loweralpha]
. Understand what content of the ECF should be covered in each training
session; and
.  Develop and deliver high quality training programmes based on the
training outlines.

|===

. The Services required for National Roll-Out
[arabic]
.. Product and Service 5: ECT Training Programmes (including ECT
Training Content and ECT Training Delivery)
.. A critical component of the support the DfE is offering to ECTs
during the strengthened induction is the ECT Training Programmes. The
purpose of ECT Training Programmes is to deepen ECTs’ understanding of
the content of the ECF, in order to improve the quality of their
teaching and to enable ECTs to build effective support networks,
including outside of their school. Contractors shall create and deliver
training direct to ECTs. This training shall be based on one of the
Early Roll-Out Core Induction Programme’s ECT Training Session Outline
(Product 4), and Contractors are required to ensure the outcomes set out
in those Training Session Outlines are met.

.. Product 5a: ECT Training Programme Content

.. Table 3 - sets out the essential criteria for the ECT Training
Content to be met by Contractors when designing the ECT training
programme:
+
[width="100%",cols="5%,95%",options="header",]
|===
2+|*Product 5a: Essential criteria for ECT Training Programmes*
a|
[arabic]
. {blank}

|The Training Programme Content must only cover content referred to in
the ECF.

a|
[arabic, start=2]
. {blank}

|Sufficient ECT Training Content shall be produced to best utilise the
time allocated in the relevant Sequence for ECT Training Sessions.

a|
[arabic, start=3]
. {blank}

|The ECT Training Content shall adhere to the relevant ECT Training
Session Outlines (Product 4).

a|
[arabic, start=4]
. {blank}

|The approach to ECT training shall be informed by (and make reference
to) current research and international best practice.

a|
[arabic, start=5]
. {blank}

|In designing ECT Training Content, the Contractor must give due
consideration to different delivery methods, including but not limited
to face-to-face sessions, peer sessions, events and/or visits, online
sessions, and communities of support. Of the 30 hours of training, there
must be a minimum of 18 hours of face-to face ECT training provided. The
Contractor must ensure that the ECT training sessions help ECTs to build
effective support networks, including outside of their own school, and
must ensure that the ECT Training Sessions allow ECTs to observe a range
of good practice and teaching methods whilst minimising the impact on
ECTs’ time and workload.

a|
[arabic, start=6]
. {blank}

|The Contractor must produce Training Programme Content that works for
all ECTs, regardless of subject, phase, or context. This can either be a
universal programme of content suitable for all ECTs, drawing from a
range of subject, phases and contexts or separate sets of content which
are subject, phase and/or context specific.
|===

.. Service 5b: ECT Training Programme Delivery

.. Table 4 – sets out the essential criteria for the ECT Training
Delivery to be met by Contractors when delivering the ECT Training
Programme.
+
[width="100%",cols="5%,95%",options="header",]
|===
2+|*Product 5b: Essential criteria for Training Programme Delivery*
a|
[arabic]
. {blank}

|The Contractor must deliver the ECT Training Content to all ECTs in
schools who have signed-up to the Contractor’s Programme in National
Roll-Out. The ECT Training Programmes must not exceed the time allocated
in the relevant Sequence for ECT Training.

a|
[arabic, start=2]
. {blank}

|The Contractor has primary responsibility for the delivery of the ECT
Training Programme, including for the quality of provision delivered by
any sub-contractors, as measured by Key Performance Indicators (KPIs)
and/or Service Level Agreements (SLA).

a|
[arabic, start=3]
. {blank}

|The Contractor must work with schools to ensure high participation in
training programmes, providing evidence for how the programme will meet
the needs of schools and ECTs, including recognising timetabling
considerations.

a|
[arabic, start=4]
. {blank}

|The Contractor shall develop mechanisms for accurately measuring and
reporting participation and retention rates in the programme and have
mechanisms and strategies for improving low participation and retention
rates.

a|
[arabic, start=5]
. {blank}

|The Contractor must ensure that the information and data that it holds
in relation to each ECT Participant is in a format that can be shared
easily. In addition, that its registration with the Information
Commissioner’s Office enables the Contractor to provide information to
the DfE, should one of its ECT Participants move schools and therefore
training programmes to another Contractor.
|===

.. Product and Service 6: Mentor Training Programmes (including Mentor
Training Content and Mentor Training Delivery)

.. In order to support Mentors to develop a deep understanding of the
ECF; to improve and tailor their support to individual ECTs; and to
develop a professional community of support to share best practice, the
Contractor is required to develop and deliver training for the Mentors
of ECTs.

.. Product 6a: Mentor Training Programme Content

.. Table 5 – sets out the essential criteria for the Mentor training
content to be met by Contractors when designing the Mentor Training
Programme Content:
+
[width="100%",cols="5%,95%",options="header",]
|===
2+|*Product 6a: Essential criteria for Mentor Training Programme Content*

a|
[arabic]
. {blank}

|The Contractor must produce Mentor training content that is focused
primarily on training Mentors in: (i) proficiency in the content of the
ECF; and (ii) building core mentoring knowledge and skills needed for
the relevant Core Induction Programme’s Mentor Sessions. These will
ensure that the Mentor can support the ECT to understand the ECF.

a|
[arabic, start=2]
. {blank}

|The Contractor must develop a Mentor Training Programme that provides
for a maximum of 36 hours of training for Mentors over two years. This
equates to approximately 6 hours of training per term (based on a school
that operates a three-term academic year); the Contractor is not bound
by this model and may use their 36 hours as is most appropriate. The
design of the Mentor Training Programme must take account of the
existing burdens on Mentors and schools.

a|
[arabic, start=3]
. {blank}

|The Mentor Training Programme Content must be informed by (and make
reference to) current recognised research and international best
practice.

a|
[arabic, start=4]
. {blank}

|In designing the Mentor Training Programme Content, the Contractor must
give due consideration to different delivery methods, including but not
limited to face-to-face sessions, peer sessions, events and/or visits,
online sessions, communities of support. There must be a minimum of nine
hours of face-to-face training. The Contractor must ensure that the
training programme helps Mentors to build effective support networks,
including outside of their own school whilst minimising the impact on
Mentors’ time and workload.

a|
[arabic, start=5]
. {blank}

|The Contractor must ensure that all Mentor training fully adheres to
the current
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/536891/Mentor_standards_report_Final.pdf[[.underline]#National
Standards#] for school-based initial teacher training Mentors. The DfE
reserves the right to require the Contractor to make reasonable
adjustments to the Mentor training following any future publication of
updated standards and/or frameworks.

a|
[arabic, start=6]
. {blank}

|The Contractor must produce Mentor training content that works for all
Mentors, regardless of subject, phase or context. This can either be a
universal set of training content suitable for all Mentors, drawing from
a range of subject, phases and contexts or separate sets of training
content which are subject, phase and/or context specific.
|===

.. Service 6b: Mentor Training Programme Delivery

.. Table 6 – sets out the essential criteria for the Mentor training
delivery to be met by Contractors when delivering the Mentor Training
Programme.
+
[width="100%",cols="5%,95%",options="header",]
|===
2+|*Product 6b: Essential criteria for Mentor Training Programme Delivery*

a|
[arabic]
. {blank}

|The Contractor must deliver the Mentor Training Programme Content to
all the ECT Mentors in all the schools that they propose to deliver in,
as per the recruitment requirements below.

a|
[arabic, start=2]
. {blank}

|The Mentor Training Programme must not exceed the time allocated in the
relevant Sequence. The 36 hours of content can be delivered across the
two years at the Contractor’s discretion.

a|
[arabic, start=3]
. {blank}

|The Contractor has full responsibility for the quality of the delivery
of the Mentor Training Programme, including for the quality of any
sub-contractors.

a|
[arabic, start=4]
. {blank}

|The Contractor must work with schools to ensure high participation in
Mentor training Programmes, providing evidence for how the programme
will meet the needs of schools, including recognising timetabling
considerations.

a|
[arabic, start=5]
. {blank}

|The Contractor shall develop mechanisms for accurately measuring and
reporting participation and retention rates in the programme and have
mechanisms for improving low participation and retention rates.

a|
[arabic, start=6]
. {blank}

|The Contractor must ensure that the information and data that it holds
in relation to each Mentor Participant is in a format that can be shared
easily. In addition, that its registration with the Information
Commissioner’s Office enables the Contractor to provide information to
the DfE, should one of its Mentor Participants move schools and
therefore training programmes to another Contractor.
|===

. Commissioning of Delivery Partners
[arabic]
.. It is expected that the Contractors will deliver their ECF Full
Induction Programme in partnership with Delivery Partners. These will be
other high-quality organisations including the national network of
Teaching School Hubs (TSH) which will be in place in early 2021. It is
expected that high quality education training Contractors including TSH,
will play a key role in the delivery of the ECF.

.. The DfE’s strong preference is for Delivery Partners to work
exclusively with one lead Contractor. However, in the event a Delivery
Partner works with more than one Contractor, each of the Contractors
engaging the same Delivery Partner is responsible for managing any
emerging conflicts of interest. As part of each Service Proposal the
Contractor shall ensure that it has considered, and where required,
mitigated any potential conflicts of interest, commercial sensitivities
and/or data protection risks. Each Contractor is responsible for
identifying and managing any such instances within their supply chain
and shall implement a proportionate policy or code of conduct, as
required. The Contractor shall notify the DfE in its Service Proposal
and subsequently where conflicts of interest are identified and shall
keep records of compliance to be made available to the DfE on request.

.. The Contractor is responsible for all legal and audit obligations of
their supply chain, including adhering to government policy regarding:
SMEs, supply chain prompt payment, compliance and managing conflicts of
interest.

.. The Contractor shall hold their Delivery Partners to account for
fulfilment of this contract. To this end, the Contractor must have a
clear and documented strategy setting out their management and other
arrangements for delivery partners, including:
[arabic]
... The role and scope of Delivery Partners and the arrangements to be
put in place between the parties, including the performance management
of the Delivery Partner;

... Clear criteria that will be used to select Delivery Partners which
must as a minimum meet the DfE’s criteria set out in Table 7;

... Arrangements for onboarding and training Delivery Partners to the
required standard when appointed;

... How the Contractor will manage Delivery Partners effectively to
ensure high quality delivery including quality assurance processes,
audit and governance arrangements, and remediation and contingency plans
in the event of poor performance or failure;

... How Delivery Partners will execute communications and marketing on
the Contractors’ behalf in line with government policy and the
communication and marketing plan signed off by DfE; and

... How the lead Contractor will use Delivery Partners’ branding and
vice versa when carrying out communication and marketing where
appropriate.

.. Table 7 – The Contractor shall as a minimum meet the requirements
set out in Table 7 in relation to the selection of the different types
of Delivery Partners as part of its supply chain.
+
[width="100%",cols="53%,47%",options="header",]
|===
|C**ommercial organisations, Charities, HEIs and consultants**
|*Schools*
a|
* Parts 1 & 2 of the Standard Selection Questionnaire.
* No unmanageable conflicts of interest or reputational risk to the ECF.
* No unresolved performance issues, as identified by the QA function.

a|
* Must be graded Good or Outstanding for overall effectiveness by
Ofsted.
* No unmanageable conflicts of interest or reputational risk to the ECF
and/or the DfE.
* No unresolved performance issues, as identified by the QA function
and/or by the DfE.

|===

.. The DfE reserves the right to undertake due diligence on any of the
Contractors Delivery Partners to ensure compliance with the minimum
criteria in Table 7.

. Targeting
[arabic]
.. The Contractor is required to recruit and deliver training to ECTs
and their Mentors in line with the cohort specific targeting requirement
set out by the DfE. The Contractor will need to ensure their recruitment
targeting incorporates the framework KPIs and any additional
geographical or school level targets as outlined for each cohort.

.. The Contractor shall ensure they obtain written agreement which
should be in the form of a Memorandum of Understanding (MoU) or contract
with schools to confirm that they have agreed to sign up to their
training offer. Prior to issuing the MoU/Contract to schools, the
Contractor shall provide the DfE with a copy of their proposed wording
for review and clearance. The requirement is to train a Mentor for each
ECT participating in the programme. However, it is recognised that there
will not be a one:one ratio in every case. In the case that an ECT has
more than one Mentor, only the main Mentor is automatically entitled to
participate in the Mentor Training.

.. The Contractor shall send notification via the DfE digital platform
within 5 working days of entering into an agreement with a school to
deliver the Full Induction Programme.

.. The Contractor is not permitted to charge schools for any of the
National Roll-Out services or offer any financial (or equivalent)
incentives linked to recruitment.

.. The Contractor shall work with the DfE and other framework
Contractors where possible, to ensure that their targeting reflects
national demand and is not heavily focussed on areas targeted by
multiple framework providers.

.. The Contractor, where necessary to meet national demand, shall
collaborate with other ECF Providers and Teaching Schools Hubs.

. ECTs and Mentors: Part-time, Reduced Inductions, Portability
[arabic]
.. The Contractor shall ensure their training/content is suitable for
take up by Part-time ECTs, ECTs who have an extended induction,
including to account for breaks in induction such as maternity leave,
and those who move schools during induction. In the latter situation
where the ECT moves schools mid induction, Contractors shall ensure that
the ECT is able to continue with their original Contractor unless there
is an exceptional circumstance such as the ECT moves to a different
geographical area that is not covered by the original Contractor. In
such a situation, the DfE will not make any further output payments to
the initial Contractor as they will no longer be delivering to the ECT.

.. The Contractor must ensure their training/content works for ECTs
undertaking a reduced term of induction of at least 1 academic year.
Reductions will be decided by Awarding Bodies, and guidance on content
to be covered on reduced inductions will be provided by the DfE.

.. For each cohort, unless instructed otherwise by the DfE, the
Contractor must have a policy, on ECTs undergoing an extended or reduced
term of induction, Part-time ECTs and ECTs transferring schools during
their training/induction period. The contractor must submit this policy
to the DfE on 9^th^ April 2021 for the 2021 cohort. Contractors shall
update this policy and resubmit as part of its Service Proposal for each
new cohort ensuring it incorporates all further guidance provided by the
DfE.

.. The Contractor must also ensure that their training/content works
for part time mentors, and those who may take a break from working, such
as for maternity leave, and those who move schools during the training.
In the latter situation, the mentor will continue with their original
Contractor unless there is an exceptional circumstance, as outlined
above.

. Communications and Marketing
[arabic]
.. All spend on communication and marketing activity within the scope
of the Government Communications Service (GCS) Professional Assurance
(PASS) controls is restricted. The PASS is the Cabinet Office process
through which, the DfE gains approval for all communications spend. The
Contractor shall base their delivery models on the assumption that only
communications and marketing activity that is outside the scope of the
PASS, in other words no-cost activity, is permitted. Activities
considered in scope of PASS may only be undertaken with prior approval
from the Cabinet Office and the DfE. Activity considered in scope of
PASS is:
[arabic]
... Advertising including TV; radio; digital advertising; outdoor;
print; advertorials; recruitment; costs of media; fees and commission
for media buying; media planning; creative development and production;

... Marketing activities including: design and branding; direct and
relationship marketing; customer relationship management programmes;
telemarketing; campaign help lines; partnership marketing; sponsorship
marketing; field or experiential marketing; merchandising; advertiser
funded programming; audio-visual activity; storage and distribution of
marketing materials;

... Consultation activities including associated publicity, events,
resources and materials, research, analysis and evaluation;

... Communication strategy, planning, concept and proposition testing
and development;

... Market research that informs marketing and advertising activity
and evaluation of marketing and advertising activity;

... Printing and publications;

... Events, conferences and exhibitions, including stakeholder,
public and internal communication events, but excluding training events;

... Public relations (PR) activity; and

... Digital activity including website and application development;
search engine marketing, including pay-per-click; digital display
advertising; content partnerships; email marketing; mobile and SMS
marketing; interactive online content.

.. The DfE will engage with the GCS prior to each cohort and where
approval is received for any restricted communications and marketing
activity, only then will the Contractor will be able to apply to
undertake in scope activity as outlined in paragraph 12.1. PASS
approvals will be limited to a single cohort and the Contractor must
seek prior approval for any proposed activity from the DfE via the
cohort Call-off process.

.. Therefore, the Contractor shall base their delivery models on the
assumption that only communications and marketing activity that is
outside the scope of the PASS, in other words no-cost activity, is
permitted. Examples of such activities are:
[arabic]
... Non-paid social media posts;
... Email campaigns;
... Webinars/ online engagement events;
... networking, engagement, and other business development activity
related to the recruitment of schools and delivery partners.

.. The Contractor shall utilise permitted Communications & Marketing
activity to raise awareness of, and increase demand for, the
professional development for ECTs based on the ECF, as well as to
increase opportunities to achieve targets for generating demand and
registrations. This should be done through engaging school leaders and
ECTs and providing a platform to facilitate registrations. The
Contractor must be flexible and proactive in adapting their delivery to
align with wider DfE Communications and Marketing activity and Cabinet
Office guidance. This will be in line with any changing landscapes to
ECF, the DfE and government priorities.

.. The Contractor will be required to develop a targeted
Communications & Marketing plan for each Call-off, evidencing alignment
with the requirement set out in the Communications and Marketing section
of the Service Specification, which will require sign-off by the DfE.
The DfE may request adaptations in reaction to changing landscapes
should they occur. The Communications & Marketing plan must, as a
minimum, include:-
[arabic]
... A list of all proposed activities, inclusive of events (virtual
or physical) and marketing activities;

... A clear outline of the cost (if applicable) associated to each
proposed marketing activity (agreement with the DfE will be required
prior to commencement of any marketing activity); and

... A clear timeline of when each activity will be conducted and if
applicable, any milestones the activity aligns to i.e. teacher
resignation dates.

.. In the event that DfE does not approve the activity referenced in
12.5.1 the Contractor shall be required to continue to deliver the
Service using other approaches that do not require PASS clearance.

.. The Contractor shall adhere to government guidelines when designing
marketing materials. Guidelines will be provided upon award of contract
and will be updated regularly where needed.

.. Where the Contractor plans to use language in communications that
has not previously been signed off by the DfE, the Contractor must
submit the marketing materials 5 working days ahead of publication for
the DfE to review. The DfE will provide comments and or clearance within
3 days. In the event the DfE expects the Contractor to make changes,
these must be carried out with the marketing materials resubmitted to
the DfE for clearance before publication.

.. The Contractor shall submit all media plans and materials (e.g.
press releases, media interviews or media statements) for clearance by
the DfE’s press office. These materials / plans should be sent at least
48 hours in advance (not including weekends) of their proposed use. The
Contractor shall consider all required amendments from the DfE press
office.

.. The Contractor shall design and host a digital landing page that
provides schools and ECTs with thorough information on the ECF, and a
clear step-guide on how to register an interest and sign-up via the DfE
service (see Digital Delivery Standards for further requirements). The
Contractor landing page shall align with the DfE’s ECF landing page. DFE
will make data captured from schools and ECTs available to assist in the
registration process for Contractors’ own platforms, through which the
ECF induction will be carried out. The Contractor is required to submit
the proposed page to the DfE for sign-off 5 working days ahead of
publishing to ensure consistent language is being used.

.. The Contractor must ensure Management Information relating to the
Communications & Marketing service is captured and reports are made
available to the DfE at agreed times.

.. When requested by the DfE, the Contractor shall provide further
analysis and evaluation of its Communication & Marketing activities,
including insights on which channels are the most effective to raise
awareness and increase registrations for the ECF. The Contractor’s
analysis shall also include intel on schools’ and ECTs’ perceptions and
behaviours towards ECF (via quantitative and qualitative data). The
Contractor shall provide ideas and recommendations on how best to
positively influence the sector.

.. To maximise on raising awareness of the ECF, the DfE will carry
out its own DfE-led communications and marketing activities. The DfE
will do this by utilising its own network of stakeholders, commissioning
all no-cost communications and marketing activities available to its
disposal and, at its own discretion and subject to approvals), this may
include “paid” campaigns, including, but not limited to, Google AdWord
and social media campaigns. The Contractor shall not seek to place any
reliance on such DfE led awareness raising activity within their tender
submission.

. Digital Delivery Standards
[arabic]
.. At DfE we follow
https://www.gov.uk/guidance/government-design-principles[[.underline]#government
design principles#] to ensure that we develop and deliver digital
experiences to the highest quality.

.. The Contractor must share their work with DfE early and often to
ensure these expectations are being met and to gain guidance where
needed.
https://www.gov.uk/guidance/government-design-principles#do-less[[.underline]#https://www.gov.uk/guidance/government-design-principles#do-less#]

.. The DfE will develop, host and manage a digital platform to
register the schools and teachers who will be accessing the Full
Induction Programme offered by the Contractor and other framework
providers. The DfE digital platform will also host advice and guidance
about the Early Career Framework programmes on offer to schools.

.. The DfE will provide the Contractor with timely access to the
participant data in order to set up user accounts and manage progress
and attendance on the Contractor’s platforms.

.. Participant data, such as TRN, name and date of birth for ECTs,
will be validated by DfE before being shared with the Contractor.

.. The Contractor shall develop, host and manage a digital platform
with the capability of hosting the Contractor’s Full Induction
Programme, and the Core Induction Programme that they have selected,
including the following elements:
[arabic]
... Product 1 – Sequence

... Product 2 – Self-directed Study Materials (including user
interaction with content such as watching videos, saving progress and
quiz scores)
[arabic]
... Product 3 – Mentor Session Materials

... Product 4 – ECT Training Session Outlines

.. Schools will be able to view a sample of each Core Induction
Programme on the DfE digital platform before committing to doing the
Full Induction Programme with a Contractor.

.. To deliver the Full Induction Programme, the Contractor shall also
provide and host the additional products:
[arabic]
... Product 5 – ECT training (based on Product 4 outlines)

... Product 6 – Mentor Training

.. The Contractor must be able to provide DfE with training attendance
data to evidence ongoing engagement with the Full Induction Programme.

.. The Contractor will have access to the DfE digital platform to
notify the DfE of the schools they have signed agreements with to
deliver the Full Induction Programme.
+
*Integration with DfE’s digital service*
+
*Creating an accessible, joined up service*

.. The Contractor must work with the DfE to test the end-to-end
journey where there are integration points, including for example, the
transition of user data from the DfE’s digital platform to the
Contractors.

.. Usability testing on the Contractor’s platform must be carried out
with representative users of the service including those who are low on
the digital inclusion scale, have impairments or are from Remote and
Disadvantaged Areas. Insight from the Contractor’s user testing, as well
as feedback from users of the live service, must be shared with DfE and
used to develop, resolve issues and continually improve the services.

.. Prior to the commencement of the programme, and then reviewed at
periodic points throughout service delivery, the Contractor shall be
required to audit their compliance with WCAG 2.1 level AA accessibility
requirements and identify opportunities to improve accessibility as part
of testing, feedback, and continuous improvement. In line with the
Public Sector Bodies (Websites and Mobile Applications) Accessibility
Regulations 2018, the Contractor must make their platform accessible and
publish an Accessibility Statement. See
https://www.gov.uk/guidance/make-your-website-or-app-accessible-and-publish-an-accessibility-statement#publish-your-accessibility-statement[[.underline]#here#]
for more details.

.. The Contractor’s platform must be resilient and responsive across
devices and operating systems that users use. As a minimum the
Contractor must test their digital service works in browsers specified
in the GOV.UK Service Manual
+
*Branding considerations and consistent language*

.. Working closely with DfE the Contractor is required to ensure
branding and language are used consistently throughout the full service,
e.g. on communications, making it clear to users who they are
communicating with and keeping them orientated within the journey,
regardless of the channel being used.

.. Where attachments, downloadable PDFs or print-friendly versions
are provided on Contractor’s platform then in addition to the HTML
content, the Contractor shall ensure they are accessible by having a
logical structure based on tags and headings, meaningful document
properties, readable body text, good colour contrast and text
alternatives for images. More information on
https://www.gov.uk/guidance/how-to-publish-on-gov-uk/accessible-pdfs#check-a-pdf-for-accessibility[[.underline]#accessible
PDFs#] is available on GOV.UK and at
https://support.microsoft.com/en-us/office/create-accessible-pdfs-064625e0-56ea-4e16-ad71-3aa33bb4b7ed?ui=en-us&rs=en-us&ad=us[[.underline]#Microsoft.#]
+
*Communications and notifications*

.. Notifications to users must be triggered at the right place in the
journey to satisfy the needs of end users for example, account creation
notifications for the Contractor’s platform.
+
*GDPR compliance*

.. Where personal data is held by the Contractor, it must comply with
GDPR requirements, notifying users of what data is being held, who has
access to it and how to change permissions on its use. Further details
regarding GDPR can be found in the Framework Agreement and Call-off
Contract (note to add specific references).
+
*User feedback and analysis*

.. The Contractor shall provide opportunities for users to give
feedback on their service via digital and other channels e.g. via
service support, complaints processes, phone, feedback forms.

.. The Contractor shall detail their process for reviewing user
feedback, ensuring issues are communicated to DfE as appropriate and
resolved in a timely manner. The Contractor shall set out their approach
to achieve continuous service improvement in consultation with DfE.
+
*Platform requirements and future proofing*

.. Suitable assurance certification shall to be provided in the form
of IS02700 or equivalent. As a minimum the Contractor shall provide
evidence that it holds and thereafter maintains Cyber Essentials
certification.

.. The Contractor must ensure that all digital elements delivered as
part of their Service and any Ordered Services, including by any
Delivery Partners:
[arabic]
... undergo and pass a
https://www.gov.uk/service-manual/technology/vulnerability-and-penetration-testing[[.underline]#penetration
test#] before the launch date and periodically thereafter for the
lifetime of the platform.

... have operational security processes in place.

... have a documented process for managing source code.

... have a documented process for changing, upgrading or deploying
new versions of the software.

... provide evidence that these activities have been conducted,
highlighting the risks found and mitigations applied.

.. Perform assurance processes iteratively and continuously
throughout both the “implementation” and “live” periods of the
platform’s lifecycle. Assurance is conducted throughout the delivery
phase. The Digital Service Standard encourages an Agile style of
delivery where demos (rather than slide decks) of working software and
prototypes are given frequently. This is a key part of our governance
process and substantially reduces the burden of more formal engagements.

. Independent Evaluation

.. Working with the EEF, the DfE will ensure that national roll out of
the ECF is evaluated in order that lessons are learned for future
delivery. The nature of this evaluation will be determined in due
course. However, there are a number of associated requirements for
Contractors that need to be factored in to planning. 

.. The aim of the evaluation will be to ensure that delivery is
meeting the needs of ECTs, Mentors and schools. The scope of the
evaluation and detail of the method are still being developed. Broadly,
this is likely to be both a process evaluation focussing on the
successes and challenges during implementation; as well as an impact
evaluation assessing the impact of the Full Induction Programme on both
teacher retention and teaching quality.

.. Whilst the DfE will endeavour to ensure that any evaluation
activity is proportionate and low burden to all, it is a requirement of
the contract that Contractors participate and ensure that schools,
mentors ECTs are aware of the importance of engaging in the evaluation
and encouraged to respond. It is a condition of contracting that
Contractors will be required to commit to supporting continuous
improvement by sharing knowledge and experiences of the successes and
challenges faced, with the independent evaluator, QA function and the
DfE.

. Governance
[arabic]
.. The Contractor shall put in place and maintain effective management
arrangements throughout the Framework Agreement Period. The Contractor’s
management arrangements shall include (without limitation) arrangements
to ensure that:
[arabic]
... The Services are delivered in accordance with this Framework
Agreement;

... The needs of Participants are fulfilled;

... The Services are delivered to a high quality throughout the
Framework Agreement Period; and

... Effective quality assurance and improvement processes are in
place.

.. The Contractor shall ensure that the Services are flexible and
responsive to suggestions and requests put forward by the DfE.

.. The Contractor shall have a clear plan for continuous review of the
programme effectiveness (including how this will involve Participants in
making positive changes to the programme year upon year).

.. The Contractor shall share information and work with the DfE to
make changes and/or improvements to the services. The Contractor is
required to continually assess, monitor, and reflect geographical areas
of particular need within their strategy for increasing engagement and
recruitment to the programme.

.. The Contractor shall attend and proactively participate in any
joint collaborative meetings that the DfE convenes. These meetings will
cover, but not be limited to: emerging challenges, joint solutions,
recruitment, sharing best practice and lessons learnt, exploring
opportunities for efficiency/resource improvements, and identifying
future opportunities to work more collaboratively with the DfE and/or
other framework Contractors.

. Risk Management and Exit Arrangements
[arabic]
.. The Contractor shall develop and maintain a robust risk management
process covering all elements of the Service, this shall include but not
be limited to the accurate identification of key risks to their
programme, an understanding of risk triggers and an effective use of
mitigation and contingency planning.

.. For consortiums, the lead Contractor shall be responsible for
ensuring there are plans in place to ensure business continuity and
continuation of contract delivery, including in the event that a member
leaves the consortium for any reason, how this gap in service provision
will be met and how it will be ensured that the contract continues to be
delivered to agreed standards.

.. The Contractor shall set out its proposal for the effective
management of contract exit including in the event of a transfer to a
new Contractor in the case of a change of Contractor or to the DfE. As a
minimum the Exit plan shall include but not be limited to: staffing; the
safe transfer of any data owned by the DfE; timescales for any transfer;
licensing requirements for software; and documentation covering any
bespoke software that has been developed.

.. The Contractor shall agree a revised exit agreement and plan with
the DfE within 6 months of each Call-off Contract start date.

. Management Information
[arabic]
.. The DfE will have Service Levels regarding the collection and
management of data. Further details are included in Schedule 7 of the
Framework Agreement and Part 2 of Schedule 2 of the Call-off Contract.

.. Throughout the term of each Call-off Contract, the Contractor will
be required to collect a range of data to inform contract management
discussions, reporting against milestones and KPIs as well as to support
the independent evaluation. The requirements will include the collection
of data about schools that are involved in the programme, including a
named contact for communications from the Contractor, the DfE,
Appropriate Body, Independent Evaluator or Quality Assurance function,
as well as those schools contacted but not participating. The Contractor
will also be required to manage data about the participants (both ECTs
and Mentors) involved in the programme to allow for data matching and
analysis as well as verification and evaluation purposes. The Contractor
must ensure that it and its Delivery Partners secure the necessary
informed consents and have in place data-sharing agreements in relation
to the schools and participants recruited to the programme such that the
Contractor can collate and share the data with the DfE.

.. The Contractor shall evidence its capability and capacity to handle
data at scale and the ability to collect and share the details of a
minimum 1,000 ECTs and their assigned Mentors in year 1 and a minimum of
2,000 in subsequent years.

.. DfE will work with the Contractor during the Annual Cohort
Competition mobilisation stage to agree how MI will be collected and
submitted. Given the range of systems organisations may use, DfE expect
to provide a digital interface for data collection through manual entry.
However, DfE will also explore the option to make use of an
API/messaging interface with the Contractor where appropriate.

.. The DfE have identified the following core data to be collected per
cohort, although DfE reserves the right to revise this at the Call-Off
stage:
[arabic]
... schools who have signed agreements with the Contractor;

... number of participants by type (ECT, mentor) and working pattern
(full/part time, reduced course) per school;

... status of each participant i.e. started, retained, deferred,
completed, withdrawn;

... expected number of self-study modules completed by date, and
number completed per participant;

... training events attended (in person, online);

... post-session training events watched (recording); and

... dates of mentor sessions attended.

.. Data will be submitted by the Contractor prior to output payments,
according to the conditions set out in the Call-Off Contract. Where it
is possible, a change in data should be passed to DfE as soon as it is
known.

.. As a contingency in the instance that a digital interface or API is
not available for data collection, DfE will provide a spreadsheet
template to be completed and returned securely using Galaxkey to
mailto:ECF.DELIVERY@education.gov.uk[[.underline]#ecf.delivery@education.gov.uk#].
Instructions on how to register and use Galaxkey will be provided. The
Contractor shall submit the updated spreadsheet monthly to DfE, adding
any new schools or teachers or amending records where the status of the
school or Participant has changed.

.. When spreadsheets are used, the DfE will then complete a validation
check of the information submitted and where appropriate provide an
updated version of the template for continued use. The DfE will use the
data submitted to validate the Contractor’s claims for payment and
therefore it is of vital importance that the information submitted is
both reliable and timely.

.. The Contractor shall work with the DfE to rectify any discrepancies
identified immediately.

.. As part of the recruitment, the Contractor is responsible for
collecting the details of all schools contacted and any Participant
recruited onto the programme. As a minimum the DfE require the
Contractor to collect the following data:
[arabic]
... *School* - URN, contact details of the Induction Co-ordinator
(including name, telephone number and email address), date school signed
up, date school withdrew/reason for withdrawal when appropriate and
reason for school not signing up with the Contractor.

... *Participant* – TRN, role, name, date of birth, working pattern,
email address, date Participant signed up, confirmation of Participants
continued involvement and reason for withdrawal and/or deferral where
applicable.

.. For the avoidance of doubt, the Contractor is responsible for the
collection of data including data collected by any Delivery Partners and
ensuring this is collected in a timely, secure, consistent and compliant
manner. The Contractor shall set out the methodology by which it will
assure data collection and quality assurance across its supply chain.
The DfE will validate any data submitted related to payments and
Contractors will be required to submit all data in the format determined
by the DfE.

.. Paragraph 17 sets out the default position for the collection and
submission of Management Information. However, as per paragraph 27,
where opportunities to improve the process are identified, the DfE
reserves the right to amend this paragraph 17. Any changes to the
process will be subject to the Framework Agreement and/or Call-off
Contract change control procedure.

== SCHEDULE 4 – CALL OFF PROCEDURES

[arabic]
. *DEFINITIONS*
[arabic]
.. In this Schedule, the following definitions shall apply:
+
Annual Cohort Competition:: means awarding a Call-off Contract for a scheduled annual cohort of
services through the Framework subject to competition, as specified in
paragraph 4.
+
The intention is for the Department to run an Annual Cohort Competition
for each Academic Year during the term of the Framework;

Direct Award:: means awarding a Call-off Contract for ad-hoc services through the
Framework without further competition, as specified in paragraph 3.

Further Competition:: means awarding a Call-off Contract for bespoke services through the
Framework subject to competition, as specified in paragraph 5;

Local Authority District:: means the local government divisions of England;

Minimum Recruitment Target:: means the minimum cohort recruitment targets as detailed at paragraph 26
of Schedule 7;

Service Requirement:: means the specification of the Departments want or need;

Statement of Service Requirement:: means a written definition of the Departments Service Requirement;

Template Call Off Terms:: means the model Call-off Contract at Schedule 2

. AWARD PROCEDURE
[arabic]
.. If the Department decides to source the Services through this
Framework Agreement, then it will award Call-off Contracts in accordance
with the procedure in this Schedule and the requirements of the
Regulations and the Guidance. For the purposes of this Schedule,
“*Guidance*” shall mean any guidance issued or updated by the UK
Government from time to time in relation to the Regulations.
.. If the Department can determine that:
[arabic]
... its Service Requirement is substantially similar to the description
of the Services as set out in Schedule 3 (Specification); and
... all of the terms of the proposed Call Off Contract are laid down in
this Framework Agreement and the Template Call Off Terms do not require
amendment or any supplementary terms and conditions (other than the
inclusion of optional provisions already provided for in the Template
Call Off Terms); and
... the volume of unless required represents delivery to less than
1,000 ECTs and their mentors;
+
then the Department may award a Call Off Contract in accordance with the
Direct Award procedure set out in paragraph 3 below.
[arabic]
.. If the Department can determine that:
[arabic]
... its Service Requirement is similar to the description of the
Services as set out in Schedule 3 (Specification) but the award
procedure requires the Contractor to develop proposals or a solution in
respect of such Department’s Service Requirements; and

... all of the terms of the proposed Call Off Contract are laid down
in this Framework Agreement and the Template Call Off Terms do not
require amendment or any supplementary terms and conditions (other than
the inclusion of optional provisions already provided for in the
Template Call Off Terms); and

... the volume of services required represents delivery to 1,000 or
more ECTs and their mentors;
+
then the Department shall award a Call Off Contract in accordance with
the Annual Cohort Competition Procedure set out in paragraph 4 below.

.. If all of the terms of the proposed Call Off Contract are not laid
down in this Framework Agreement and the Department:
[arabic]
... requires the Contractor to develop proposals or a solution in respect
of the Department’s Service Requirement; and/or
... needs to amend or refine the Template Call Off Terms to reflect its
Services Requirements to the extent permitted by and in accordance with
the Regulations and Guidance;

+
then the Department shall award a Call Off Contract in accordance with
the Further Competition Procedure set out in paragraph 5 below.

. *DIRECT AWARD WITHOUT COMPETITION*
[arabic]
.. The Department may only award a Call Off Contract for Services under
this Framework Agreement without holding a further competition in
accordance with Paragraph 3.2 below.
.. Subject to paragraph 3 above the Department may make a direct award
to a Contractor without holding a further competition where the Service
Requirement is for the delivery of Full Induction Programme services for
less than 1,000 ECTs and their mentors.
.. In order to make a direct award to a Contractor without holding a
further competition the Department will develop a clear Statement of
Service Requirements and will apply the Direct Award Criteria set out in
paragraph 3.4 in order to select the Contractor that provides the most
economically advantageous solution and to whom a direct award will be
made.
.. The Direct Award Criteria shall include the Department using its
absolute discretion to make an assessment against the Contractors;
[arabic]
... performance against framework KPIs
... capacity to deliver;
... availability to deliver;
... value for money; and
... effective use of resources.
.. The Department will follow the procedure set out in paragraph 9 in
order to conclude the Call-off Contract.
. *ANNUAL COHORT COMPETITION PROCEDURE*
+
*The Department’s Obligations*
[arabic]
.. In order to award a Call Off Contract under this Framework Agreement
through the Annual Cohort Competition procedure the Department shall:
[arabic]
... develop a Statement of Service Requirements, including cohort
specific budgets, Minimum Recruitment Targets, geographical and
disadvantaged/hard to reach targets, eligible schools and Local
Authority Districts for incentive payments, and any Communications and
Marketing approval for restricted activity;
... confirm any additional award criteria to be used as per paragraph
4.5.2, and determine the specific measures and weightings or ranking to
be applied;
... amend or refine the Template Call Off Terms to reflect its Service
Requirements only to the extent permitted by and in accordance with the
requirements of the Regulations and Guidance;
... invite tenders by conducting an Annual Cohort Competition Procedure
for its Service Requirements in accordance with the Regulations and
Guidance and in particular the Department shall:
[loweralpha]
.... invite all Framework Contractors to submit a tender in writing for each
proposed Call Off Contract to be awarded by giving written notice by
email to the relevant Contractor Representative of each Contractor;
.... determine the documentation that will form the Contractors tender and
instructions on submitting a compliant tender;
.... set a time limit for the receipt by it of the tenders which takes into
account factors such as the complexity of the subject matter of the
proposed Call Off Contract and the time needed to submit tenders; and
.... keep each tender confidential until the time limit set out for the
return of tenders has expired.
... apply the Annual Cohort Competition Award Criteria (paragraph 4.3) to
the compliant tenders submitted through the Annual Cohort Competition
Procedure as the basis of its decision to award a Call Off Contract for
its Services Requirements;
... on the basis set out above, award its Call Off Contract to the
successful Framework Contractor(s) in accordance with paragraph 9 which
Call Off Contract shall:
[loweralpha]
.... state the Service Requirements;
.... state the tender submitted by the successful Contractor(s);
.... state the charges payable for the Service Requirements in accordance
with the tender submitted by the successful Contractor(s); and
.... incorporate the Template Call Off Terms (as may be amended or refined by
the Department in accordance with paragraph 4.1.2 above) applicable to
the Services,
... provide unsuccessful Contractors with written feedback in relation to
the reasons why their tenders were unsuccessful and, where in the
Departments opinion, the reasons for failure of the criteria are minor
and resolvable without significant variation to the tender submission,
allow unsuccessful Contractors an opportunity to revise and resubmit
their tenders within a reasonable timescale. The Annual Cohort
Competition Award Criteria will be applied to any resubmitted tenders
before a final award decision is made.
+
*The Contractor’s Obligations*

[arabic, start=2]
.. The Contractor shall in writing, by the time and date specified by the
Department following an invitation to tender pursuant to paragraph 4.1.3
above, provide the Department with either:
[arabic]
... a statement to the effect that it does not wish to tender in relation
to the relevant Service Requirements; or
... the full details of its tender made in respect of the relevant
Statement of Service Requirements. In the event that the Contractor
submits such a tender, it should include, as a minimum:
[loweralpha]
.... an email response subject line to comprise unique reference number and
Contractor name, so as to clearly identify the Contractor;
.... a brief summary, in the email (followed by a confirmation letter),
stating that the Contractor is bidding for the Statement of Service
Requirements;
.... a proposal covering the Service Requirements using the documents
requested by the Department;
.... confirmed supply chains; and
.... call-off specific pricing, including volume bands along with a full and
detailed breakdown of costs completed on a Department issued template
for the Minimum Recruitment Target and where relevant, a full proposal
including any additional volumes.
.. The Contractor shall ensure that any prices submitted in relation to
an Annual Cohort Competition held pursuant to this paragraph 4 shall be
based on the Charges and take into account any discount to which the
Department may be entitled as set out in Schedule 7 (Pricing).
.. The Contractor agrees that:
[loweralpha]
... all tenders submitted by the Contractor in relation to an Annual Cohort
Competition held pursuant to this paragraph 4 shall remain open for
acceptance by the Department for ninety (90) Working Days (or such other
period specified in the invitation to tender issued by the relevant
Department in accordance with the Call Off Procedure);
... all tenders submitted by the Contractor are made and will be made in
good faith and that the Contractor has not fixed or adjusted and will
not fix or adjust the price of the tender by or in accordance with any
agreement or arrangement with any other person. The Contractor certifies
that it has not and undertakes that it will not:
[lowerroman]
.... communicate to any person other than the person inviting these tenders
the amount or approximate amount of the tender, except where the
disclosure, in confidence, of the approximate amount of the tender was
necessary to obtain quotations required for the preparation of the
tender; and
.... enter into any arrangement or agreement with any other person that he or
the other person(s) shall refrain from submitting a tender or as to the
amount of any tenders to be submitted; and
... the Department will only initially award the Minimum Recruitment Target
and the award of any additional recruitment volumes proposed in the
Contractors tender is subject to the award process at paragraph 4.4 and
4.5.

+
*Award Criteria*

[arabic, start=3]
.. The Department shall use the following criteria when awarding a
Call-off Contract under the Annual Cohort Competition Procedure:
+
*Table 1 – Annual Cohort Competition Award Criteria*
+
[width="100%",cols="14%,70%,16%",options="header",]
|===
|*Criteria* | |*Weighting*
.4+|Quality a|
[.underline]#Targeting Proposals#

* A clear targeting plan, including breakdowns of targeted participants
and/or schools at a Regional, Local Authority and School level.
* Demonstration that the proposed targeting approach aligns to ECF
policy, the NRO requirement and the approach submitted as part of the
Contractor’s tender.

.4+|Pass / Fail

a|
[.underline]#Delivery Plan#

* Delivery plan demonstrating that proposal aligns to ECF policy, the
NRO requirement and the approach submitted as part of the Contractors
tender.
* Defined supply chain including specific roles and responsibilities of
each delivery partner and demonstration of alignment to ECF policy, the
NRO requirement and the Contractors strategy for managing delivery
partners as submitted in the tender.

a|
[.underline]#Implementation Plan#

* A clear mobilisation plan that demonstrates capacity to deliver the
service proposal to scale within the timescales.

a|
[.underline]#Communications and Marketing#

* A clear communications and marketing plan demonstrating that the
proposed approach offers value for money and aligns to ECF policy, the
NRO requirement and the approach submitted as part of the Contractor’s
tender.

.4+|Price a|
[.underline]#Per Participant Price#

* Volume Banded Per Participant Prices and a detailed Cost Breakdown
Structure will be required to be submitted in the Pricing Schedule
supplied by the Department. Price must not exceed £1400 per participant
for the first 2000 participants. Each subsequent volume band must be
priced lower than the previous band.
* For the purposes of the Price criteria, this will be undertaken by the
use of a ‘Weighted Average Participant Price’ model. The three Volume
Banded Per Participant Prices will be weighted in the following
proportion:
** Volume Band A: 60%
** Volume Band B: 30%
** Volume Band C: 10%
+
The respective Volume Banded Per Participant Prices will be multiplied
by the respective weighting and then added together to determine a
‘Weighted Average Participant Price’ to be used in the Price Evaluation.
* Contractors will need an ‘Average Weighted Participant Price’ within +/-
20% of the median priced successful tender.
+
Where an Average Weighted Price is more than 20% lower than the median,
the Department reserves the right to seek clarification on the
underlying price assumptions and may, at its absolute discretion, accept
the pricing where it is satisfied of its viability.

|Pass / Fail
|===
[arabic]
... The Department reserves the right to review the Annual Cohort
Competition Award Criteria prior to each Annual Cohort Competition and
where at its sole discretion make revisions to Table 1 to ensure that
the criteria remain fit for purpose and are relevant to the scope and
priorities of the cohort. The finalised Annual Cohort Competition Award
Criteria used for each annual cohort will be confirmed when inviting
tenders for the Annual Cohort Competition.

+
*2021 Cohort Award Process*

.. When awarding the 2021 Annual Cohort Competition Call-off Contract,
the Department will initially award the Minimum Recruitment Target
volume to each successful Contractor. Where budget and demand allow
volumes in excess of the Minimum Recruitment Target, the Department will
award the additional recruitment volumes, as identified in the
Contractors proposal, based on the following process.
[arabic]
... Where the combined additional recruitment volumes requested does not
exceed the cohort budget and/or demand then all Framework Agreement
Providers will receive the full recruitment volume as outlined in their
proposal.
... Where the combined additional recruitment volumes requested exceeds
the cohort budget and/or demand then proposals for additional volumes
will be ranked using the framework competition final scores and awarded
until either the demand or budget limit is met.

+
*Subsequent Cohort Award Process*

.. When awarding subsequent Annual Cohort Competition Call-Off Contracts,
the Department will initially award the Minimum Recruitment Target
volume to each successful Contractor in the Annual Cohort Competition.
Where budget and demand allow volumes in excess of the Minimum
Recruitment Target, the Department will award additional recruitment
volumes, as identified in the Contractors proposal, based on the
following process.
[arabic]
... Where the combined additional recruitment volumes requested does not
exceed the cohort budget and/or demand then all Framework Agreement
Providers will receive the full recruitment volume as outlined in their
proposal.
... Where the combined additional recruitment volumes requested exceeds
the cohort budget and/or demand then proposals for additional volumes
will be ranked and awarded until either the demand or budget limit is
met using any one or more of the following criteria;
[arabic]
.... performance against KPIs or other performance measures;
.... capacity to deliver;
.... value for money;
.... effective use of resources, including geographical coverage and priority
targeting; and
.... Social Value.
... The Department will confirm which of the above criteria are to be
used, how they will be measured, and any weightings or ranking, when
inviting tenders for each Annual Cohort Competition.

[arabic, start=5]
. *FURTHER COMPETITION PROCEDURE*
+
*The Department’s Obligations*
[arabic]
.. In order to award a Call Off Contract under this Framework Agreement
through a Further Competition Procedure the Department shall:
[arabic]
... develop a Statement of Service Requirements;
... amend or refine the Template Call Off Terms to reflect its Service
Requirements only to the extent permitted by and in accordance with the
requirements of the Regulations and Guidance;
... invite tenders by conducting a Further Competition Procedure for its
Service Requirements in accordance with the Regulations and Guidance and
in particular the Department shall:
[loweralpha]
.... invite all Framework Contractors to submit a tender in writing for each
proposed Call Off Contract to be awarded by giving written notice by
email to the relevant Contractor Representative of each Contractor;
.... determine the documentation that the Contractors will be required to
respond to and instructions on submitting a compliant tender;
.... set a time limit for the receipt by it of the tenders which takes into
account factors such as the complexity of the subject matter of the
proposed Call Off Contract and the time needed to submit tenders; and
.... keep each tender confidential until the time limit set out for the
return of tenders has expired.
... apply the Further Competition Award Criteria to compliant tenders
submitted by the Framework Contractors through the Further Competition
Procedure as the basis of its decision to award a Call Off Contract for
its Services Requirements;
... on the basis set out above, award its Call Off Contract to the
successful Framework Contractor in accordance with paragraph 9 which
Call Off Contract shall:
[loweralpha]
.... state the Service Requirements;
.... state the tender submitted by the successful Contractor;
.... state the charges payable for the Service Requirements in accordance
with the tender submitted by the successful Contractor; and
.... incorporate the Template Call Off Terms (as may be amended or refined by
the Department in accordance with paragraph 3.1.2 above) applicable to
the Services,
... provide unsuccessful Contractors with written feedback in relation
to the reasons why their tenders were unsuccessful.

+
*The Contractor’s Obligations*

.. The Contractor shall in writing, by the time and date specified by the
Department following an invitation to tender pursuant to paragraph 5.1.3
above, provide the Department with either:
[arabic]
... a statement to the effect that it does not wish to tender in relation
to the relevant Service Requirements; or
... the full details of its tender made in respect of the relevant
Statement of Service Requirements. In the event that the Contractor
submits such a tender, it should include, as a minimum:
[loweralpha]
.... an email response subject line to comprise unique reference number and
Contractor name, so as to clearly identify the Contractor;
.... a brief summary, in the email (followed by a confirmation letter),
stating that the Contractor is bidding for the Statement of Service
Requirements;
.... a proposal covering the Service Requirements using any documents that
are prescribed by the Department; and
... The Contractor shall ensure that any prices submitted in relation to
a Further Competition Procedure held pursuant to this paragraph 5 shall
be based on the Charges and take into account any discount to which the
Department may be entitled as set out in Schedule 7 (Pricing).

... The Contractor agrees that:
[loweralpha]
.... all tenders submitted by the Contractor in relation to a Further
Competition Procedure held pursuant to this paragraph 3 shall remain
open for acceptance by the Department for ninety (90) Working Days (or
such other period specified in the invitation to tender issued by the
relevant Department in accordance with the Call Off Procedure); and
.... all tenders submitted by the Contractor are made and will be made in
good faith and that the Contractor has not fixed or adjusted and will
not fix or adjust the price of the tender by or in accordance with any
agreement or arrangement with any other person. The Contractor certifies
that it has not and undertakes that it will not:
[lowerroman]
..... communicate to any person other than the person inviting these tenders
the amount or approximate amount of the tender, except where the
disclosure, in confidence, of the approximate amount of the tender was
necessary to obtain quotations required for the preparation of the
tender; and
..... enter into any arrangement or agreement with any other person that he or
the other person(s) shall refrain from submitting a tender or as to the
amount of any tenders to be submitted.

+
*Award Criteria*

[arabic, start=3]
.. The Department shall develop bespoke award criteria relative and
proportionate to the requirement using the following outline criteria
weightings when awarding a Call-off Contract under the Further
Competition Procedure:

.. *Table 2 – Further Competition Award Criteria*
+
[width="100%",cols="34%,33%,33%",]
|===
|*Criteria* |*Percentage Weightings* |*Allowable Variance*
a| Quality a| 80% a| +/- 20% (60% to 100%)
a| Price a| 20% a| +/- 20% (0% to 40%)
|===

[arabic, start=6]
. *FINANCIAL GROWTH LIMITER*
[arabic]
.. The Contractor’s Financial Growth Limiter (FGL) is set at the
Framework Award stage and determines the maximum value of business that
the Contractor can be awarded and deliver at any one time without
further evaluation or review of their financial standing. The FGL is
reviewed and determined on an annual basis at the Annual Cohort
Competition procedure, however the Contractor may submit updated
turnover information to the Department in accordance with paragraph 6.2
to request consideration of an increase to its FGL throughout the
duration of the Framework. The Contractor must submit annual turnover
values to the Department, taken from their last two years’ of audited
accounts, which will use them to calculate an average turnover. This
will be used to calculate the Contractor’s FGL. The Contractor must
submit copies of their last two years of audited accounts when
submitting their annual turnover values. The calculation used to
determine the FGL is as follows:
+
[Average turnover footnote:[Taken from previous two-years audited accounts and Order Book]* / 100] × 75 = Financial Growth Limiter

.. The Contractor can submit updated turnover information for the
Department to consider throughout the duration of the Framework to
support an increase in its FGL. The Contractor can submit additional
information such as reference to new business won or any financial
guarantees that can be provided. This additional information should be
submitted in the Order Book or by submitting separate documents if
necessary, such as more recent annual accounts, via email to the
Department. If the Contractor is seeking to increase its FGL, the
Department will undertake an economic and financial standing (EFS)
review to update the FGL. It is at the absolute discretion of the
Department as to whether the FGL will be increased. If the FGL is not
increased, the current FGL will remain in force.

.. Should a proposed Call Off Contract value result in the Contractor
exceeding their FGL, the Department may:
[arabic]
... limit the value of any Call Off Contract it awards to the FGL that is
in force at the time;
... reject the Contractor’s proposal and not award the Call Off Contract.

.. The Department may request additional information about other DfE
contracts awarded or that the Contractor is planning on bidding for and
seek assurance of the Contractor’s ability to deliver that value of
contracted business in addition to Call Offs from the Framework. This
information may be taken into consideration when setting the FGL.

. *NO AWARD*
[arabic]
.. Notwithstanding the fact that the Department has followed a procedure
as set out above in paragraph 3, 4 or 5 (as applicable), the Department
shall be entitled at all times to decline to make an award for its
Services Requirements. Nothing in this Framework Agreement shall oblige
the Department to award any Call Off Contract.

. *RESPONSIBILITY FOR AWARDS*
[arabic]
.. The Contractor acknowledges that the Department is independently
responsible for the conduct of its award of Call Off Contracts under
this Framework Agreement and that the Department is not responsible or
accountable for and shall have no liability whatsoever in relation to:
[arabic]
... the conduct of the Department in relation to this Framework
Agreement; or
... the performance or non-performance of any Call Off Contracts between
the Contractor and the Department entered into pursuant to this
Framework Agreement.

. *CALL OFF AWARD PROCEDURE*
[arabic]
.. Pursuant to paragraph 3.5 (Direct Award), paragraph 4.1.5 (Annual
Cohort Competition) or paragraph 5.1.5 (Further Competition) as
applicable, and subject to paragraph 6 (Financial Growth Limiter), the
Department will award a Call Off Contract to the Contractor by sending
(including electronically) to the Contractor the Call Off Contract terms
and conditions as substantially set out in Schedule 2 (Model Call Off
Contract) or following an Annual Cohort Competition or Further
Competition as may be amended or refined by the Department in accordance
with paragraph 4.1.2 or 5.1.2 above.
.. On receipt of the Call Off Contract as described in paragraph 8.1
from the Department the Contractor shall accept the Call Off Contract by
promptly signing and returning it (including by electronic means).
.. On receipt of the signed Call Off Contract from the Contractor, the
Department shall also sign the Call Off Contract; the Call Off Contract
shall then be formed.

== SCHEDULE 5 – CONTRACT CHANGE PROCEDURE

[arabic]
. *INTRODUCTION*
[arabic]
.. This Schedule 5 sets out the Contract Change Procedure to be used by
the Department and the Contractor to effect changes to this Framework
Agreement.
. *PRINCIPLES*
[arabic]
.. The Department and the Contractor shall conduct discussions relating
to proposed changes to this Framework Agreement in good faith. Neither
party shall unreasonably withhold or delay consent to the other Party’s
proposed changes.
.. Until such time as a Contract Change Notice (CCN) has been signed by
both Parties, the Contractor shall continue to provide and make
available to the Department the Services in accordance with this
Framework Agreement and relevant Call-Off Contracts.
.. Any work undertaken in connection with any proposed change to this
Framework Agreement by the Contractor, its Sub-Contractors or agents
(other than that which has previously been agreed in accordance with the
provisions of paragraph 2.2 of this Schedule 5) shall be undertaken
entirely at the expense and liability of the Contractor unless otherwise
agreed between the Department and the Contractor in advance.
.. Any discussions, negotiations or other communications which may take
place between the Parties in connection with any proposed change to this
Framework Agreement, including but not limited to the submission of any
written communications, prior to the signing by both Parties of the
relevant CCN, shall be without prejudice to the rights of either Party.
. *PROCEDURE*
[arabic]
.. Should either Party wish to amend this Framework Agreement, that
Party’s Framework Manager shall submit a draft CCN in the format at
Annex 1 to this Schedule 5 for discussion detailing the proposed change
to the other Party’s Framework Manager.
.. Discussion between the Parties following the submission of a draft
CCN shall result in either:
[arabic]
... no further action being taken on that draft CCN; or
... agreement between the Parties on the changes to be made to this
Framework Agreement (including agreement on the date upon which the
changes are to take effect (the “effective date”)), such agreement to be
expressed in the form of proposed revisions to the text of the relevant
parts of this Framework Agreement.
.. Where agreement is reached in accordance with paragraph 3.2.2, the
Party submitting the draft CCN shall prepare the final CCN for execution
by both Parties. The final CCN, the content of which has been agreed
between the Parties in accordance with paragraph 3.2.2 of this Schedule
5, shall be uniquely identified by a sequential number allocated by the
Department.
.. Two (2) copies of each CCN shall be signed by the Contractor and
submitted to the Department not less than ten (10) Working Days prior to
the effective date agreed in accordance with paragraph 3.2.2 of this
Schedule 5.
.. Subject to the agreement reached in accordance with paragraph 3.2.2
of this Schedule 5 remaining valid, the Department shall sign both
copies of the approved CCN within five (5) Working Days of receipt by
the Department. Following signature by the Department, one (1) copy of
the signed CCN shall be returned to the Contractor by the Department.
.. A CCN signed by both Parties shall constitute the basis of a Deed of
Variation for the purposes of amending this Framework Agreement pursuant
to Clause 5.1 of this Framework Agreement.

=== ANNEX 1 TO SCHEDULE 5*

*CONTRACT CHANGE NOTE PRO FORMA*

==== Contract Change Note for the Contract Change Procedure

[cols="1,1"]
|===
| Contract Reference Number: | unique reference number
| Sequential Number: | to be allocated by the Department’s Framework Manager
| Title: | CCN title
| Originator: | the Department / the Contractor
| Date change first proposed: | date
| Number of pages attached: | pages
|===

WHEREAS the Contractor and the Department entered into a Framework
Agreement for the provision of National Roll-Out of the Early Career
Framework services dated [date] and now wish to amend that Framework Agreement;

*Reason for proposed change*

[Party proposing change to complete]

*Full details of proposed change*

[Party proposing change to complete]

*Details of likely impact, if any, of proposed change on other aspects
of the Framework Agreement*

Party proposing change to complete

*IT IS AGREED* as follows:

. With effect from [date] it is proposed that the
Framework Agreement shall be amended as set out below:

[Details of the amendments to the Framework Agreement
to be inserted here – to include the explicit changes required to the
text in order to effect the change, i.e. Clause/Schedule/paragraph
number, required deletions and insertions etc.]

. Save as herein amended, all other terms and conditions of the
Framework Agreement inclusive of any previous CCNs shall remain in full
force and effect.

. The amendments shall be made by way of a Deed of Variation in
accordance with Clause 5.1 of this Framework Agreement.

*Signed for and on behalf of [[.mark]#the Contractor#]*

[width="100%",cols="20%,80%",options="header",]
|===
|Signature: |
|Name: |
|Title: |
|Date: |
|===

*Signed for and on behalf of the Department*

[width="100%",cols="20%,80%",options="header",]
|===
|Signature: |
|Name: |
|Title: |
|Date: |
|===


== SCHEDULE 6 – FRAMEWORK AGREEMENT PROVIDERS*

. FRAMEWORK PROVIDERS*
[arabic]
.. The following Contractors have been awarded a Framework Agreement to
deliver Services for the National Roll-Out of the Early Career
Framework:

.. Awarded February 2021:
+
* Ambition Institute
* Best Practice Network
* Capita Business Services Limited
* Education Development Trust
* Teach First
* UCL Consultants Ltd

. ADDITIONAL PROVIDERS*
[arabic]
.. Should the Department undertake any further procurements to appoint
additional providers to a Framework Agreement for the delivery of
National Roll-Out of the Early Career Framework Services, the successful
Contractors will be added to this Schedule 6 via a Change Control
Notice.

. FRAMEWORK CALL-OFFS*
[arabic]
.. All Contractors listed in this Schedule 6 will be included in any
call for competition under the Call-Off Procedures at Schedule 4,
subject to any suspension or termination rights under the terms of the
Framework Agreement or Call-Off Contracts.

== Schedule 7 – Pricing and performance

*PART 1 - PRICING*

*Charges*

[arabic]
. Where an Order is placed under the Framework without competition, the
Department shall pay the Contractor the Charges based on the Per
Participant pricing set out in Table 3b (and detailed in Annex 1) for
provision of the Services subject to satisfying the Department’s payment
conditions for the delivery of Services.
. Where a Call-off Contract is awarded via an Annual Cohort Competition
or Further Competition the Charges submitted in the Contractor’s tender
in response to the relevant call for competition will be applied to the
Call-off Contract.
. The Charges are inclusive of all expenses incurred by the Contractor
in relation to its provision of the Services and unless agreed otherwise
in writing between the Contractor and the Department, the Contractor
shall not be entitled to claim any expenses in addition to the Charges.
. Indexation shall not apply to the Charges.
. Invoices shall be submitted by the 25th of the relevant calendar month
in which the Services were delivered. For all Output Payments and set-up
and mobilisation costs, the Contractor must provide supporting evidence
that the output has been completed in the form of confirmation through
their Management Information return. The data provided will be verified
by the Department.
. At any time during the duration of the Framework Agreement (including,
for the avoidance of doubt, at any time before and/or after payment by
the Department to the Contractor) the Department shall be entitled to
validate any claim for payment made by the Contractor. At all times the
Contractor shall provide all necessary assistance as requested by the
Department (including without limitation, procuring the consent of
Service Users) to enable the Department to validate any claim for
payment made by the Contractor.
. The provisions of this Schedule shall apply to all Ordered Services
under the Framework Agreement.
. The Charges are exclusive of VAT.
. *Table 3a Charges – 2021 cohort only*
+
[width="100%",cols="55%,45%",options="header",]
|===
|*2021 cohort set-up and mobilisation costs* |[REDACTED]
|===

[arabic, start=10]
. *Table 3b: Charges Per Participant*
+
[width="99%",cols="28%,18%,18%,18%,18%",options="header",]
|===
| |*Per Participant Price (PPP)* a|
*Service Fee*

*(40% of PPP)*

a|
*Output Payments*

*(60% of PPP)*

|*Uplift Payment*
a|
*Volume Band A*

(0 – 2000 participants)

|[REDACTED] |[REDACTED] |[REDACTED] |[REDACTED]
a|
*Volume Band B*

(2001 – 4000 participants)

|[REDACTED] |[REDACTED] |[REDACTED] |[REDACTED]
a|
*Volume Band C*

(4001+ participants)

|[REDACTED] |[REDACTED] |[REDACTED] |[REDACTED]
|===
[arabic]
.. *Per Participant Price*
+
Per Participant Pricing will be used to determine the Call-off Contract
value and will be determined by the relative number of participants
recruited within each Volume Band. The first 2,000 participants will be
paid at Volume Band A, participants 2,001 up to 4,000 will be paid at
Volume Band B, and any further participants at Volume Band C.

.. *Call-off Contract Value*
+
The Call-off Contract Value will be determined by adding together the
relevant per participant costs under each of the Volume Bands based on
the agreed recruitment target for the Call-off Contract. The Call-off
Contract Value will not include Uplift Payments which will be made in
addition to the contract value as per paragraph 10.5.

.. *Service Fee*
+
The Service Fee will be a fixed amount per month, based on up to 40% of
the Call-off Contract value, divided by the length of the Call-off
Contract in months. For the 2021 cohort, the Service Fee will be
adjusted to offset the Set-up and mobilisation cost payment.

.. *Output Payments*
+
Output Payments represent the remaining 60% of the contract value and
will be made when a participant starts the programme, at retention
points (as set out in Annex 1 of Schedule 2: Part 1 – Payment Process,
of the Call-off Contract) throughout the programme for all participants
who remain enrolled, and on completion of the programme. Of the total
Output funding, the Contractor will claim 20% when a participant starts
the programme, 60% which will be split between multiple retention points
throughout the programme and 20% when a participant completes the
programme.

.. *Uplift Payment*
+
An uplift payment of £100 will be paid for each participant who comes
from a school from Local Authority Districts identified as in the top
20% most sparse in terms of schools per hectare or that has at least 40%
of pupils eligible for pupil premium, in order to incentivise
Contractors to deliver in these areas. The uplift payment will be paid
when a participant starts on the programme.

.. *Additional Services*
+
Should the Department require any ad-hoc services from the Contractor in
addition to or outside the scope of the Services and/or Per Participant
Payment model, then they shall be agreed in advance with the Department
using the Contractors pricing information at Annex 1 and/or as submitted
in the Pricing Schedule for the relevant Call-off Contract.

. The Department reserves the right to amend, or include, additional
Volume Bands in Table 3b for cohorts 2022 and beyond to reflect the
increased volumes of participants. As per the existing Volume Bandings
any additional band prices will need to be lower than the preceding
Volume Band price.
. Per participant pricing submitted via an Annual Cohort Competition or
Further Competition must be lower than the Charges in Table 3b above as
they will not include set-up costs as these will be covered in a
separate Call-off Contact. The Department reserves the right to require
Contractors to submit their Charges below the previous Cohort call-off
Charges.

=== Charges to Participants and ITT Providers

[arabic, start=13]
. Neither the Contractor nor its agents or Sub-Contractors shall levy
any charge on Participants or Schools in respect of the Services.

=== Discounts and Rebates on Cross-Subsidising Contracts

[arabic, start=14]
. The Contractor shall be obliged to make known to the Department their
appointment as a Contractor for the Department's HPITT, NPQ and/or other
ECF services or interdependent service provisions. The Contractor shall
also make known the efficiencies that will be generated from their
position across all contracts which the Department has with the
Contractor. The Contractor shall be obliged to provide management
information that includes, but not limited to, resource deployment and
information technology usage along with a costed proposal on the
discount it shall provide to the Department for the Department's
subsequent agreement.

=== Costing Management Information and Open Book Contract Management

[arabic, start=15]
. As part of the Call-Off Procedure detailed in Schedule 4, each bidding
Contractor will be required to complete a Pricing Schedule which
includes a detailed Cost Breakdown Structure and Staff Resourcing
template for the duration of the respective Cohort, if awarded. The Cost
Breakdown Structure will be itemised and provide a time series across
the delivery period. The Contractor shall provide, during the duration
of each Call-Off Contract, two updates to this structure that compares
the forecast, as submitted at the Call-off competition stage, to the
actuals at Month 12 and at the conclusion of the Cohort at Month 24. The
Contractor will also supply a monthly profile of deployed FTE for the
Cohort duration, which is updated for actuals every month and submitted
to the Department. The Department reserves the right to request detailed
information to support any actuals information as supplied by the
Contractor.

=== Service Credits

[arabic, start=16]
. The Department reserves the right to apply Service Credits as set out
in Schedule 2: Part 2 (Performance) of the Call-off Contract. However,
for the cohort starting in September 2021, the Department is not
proposing to attach Service Credits to KPIs, although for the avoidance
of doubt, Contractors will be expected to report against them and they
will remain applicable for the other performance measures, namely
Service Levels and Quality Assurance, as outlined in Schedule 2: Part 2
(Performance) of the Call-off Contract. The Department will notify the
Contractors of its intention in regard to applying Service Credits to
KPIs in future cohorts at the Annual Cohort Competition stage.

=== 2021 Annual Cohort Competition only - Set-up and mobilisation costs

[arabic, start=17]
. The Department will make funding available for set-up and mobilisation
costs for the 2021 cohort under a separate Call-off Contract, which as
per clause 20 will be offset against the value of the 2021 cohort
Call-Off Contract.
. Funding will be capped at the value in table 3a and restricted to the
activity identified in Document 5 – Pricing Schedule.
. Payments will be made following agreement of an Implementation Plan
with the Department and will be made in line with the milestones
detailed in Table 11 of Document 2 – Service Specification.
. The Department reserves the right to seek validation of the actual
costs incurred when reimbursing the Contractor for agreed set-up and
mobilisation costs and the Contractor shall ensure that where costs have
been reimbursed they will offset against the 2021 cohort charges, via a
reduction in the 2021 cohort ‘Service Fee’ equal to the amount of
funding paid under the set-up and mobilisation costs Call-Off Contract.
. If the Contractor does not successfully secure a Call-off contract for
the 2021 cohort then any set-up costs reimbursed by the Department may
be subject to recovery.

Any activity funded via the 2021 cohort Set-up and mobilisation Call-off
Contract must not be included in any subsequent cohort pricing
submissions, which should, as a result of set up and mobilisation costs
being accounted for under the separate Call-off Contract, be lower than
the 2021 cohort.

=== Benchmarking

[arabic, start=22]
. Throughout the term of the Framework Agreement the Department will
undertake performance, process performance, process and price
benchmarking at a Framework Agreement level using the information
provided by the Contractors to be included in the Framework Agreement
and as part of each Call-Off Contract. The Contractor is required to
support the Department with this work by responding to requests for
additional management information or pricing information, validated cost
breakdowns, and additional context in regard to cost drivers and
milestones. Contractors will be expected to act openly and in good faith
with all requests. Contractors may, at the Department’s discretion, also
be required to participate in collaborative and open benchmarking
exercises with other Contractors party to the Framework Agreement.
. The Department reserves the right to use anonymised framework price
benchmarking to support the development of the requirement for, and then
benchmarking of ongoing performance of, any new teacher training or ECF
service provisions.

== PART 2 - PERFORMANCE

[arabic, start=24]
. The Department will monitor the Contractor’s performance for each
Call-off Contract as set out in Schedule 2: Part 2 (Performance) of the
Call-off Contract. In addition to the individual Call-off Contract
performance monitoring the Department will also undertake the following
performance monitoring at the Framework Agreement level.

=== Minimum Delivery Targets

[arabic, start=25]
. The Contractor is required to achieve the minimum delivery targets in
accordance with Table 4.
. *Table 4 – Minimum Delivery Targets*
+
[width="99%",cols="36%,16%,16%,16%,16%",options="header",]
|===
|*Cohort starting:* |*September 2021* |*September 2022* |*September
2023* |*September 2024*
|*Minimum number of ECTs and their Mentors* |1,000 |2,000 |2,000 |2,000
|===

[arabic, start=27]
. If the Contractor fails to recruit the minimum number of ECTs and
Mentors for the start of any cohort in line with the targets set out in
table 2 the Department may at its absolute discretion:

. {empty}
[arabic]
.. in the first instance, suspend the Contractor from the Framework
Agreement in accordance with clause 7.11.1;
.. in the second instance, this will be considered a material default and
the Department may terminate the Framework Agreement as per paragraph
7.4 of this Framework Agreement.

. For the avoidance of doubt, the minimum targets in Table 4, will be
measured against the number of ECTs and Mentors recruited at the end of
October in the first year of the cohort.
. The Department reserves the right to review and amend the minimum
delivery target volumes in Table 4 in order to ensure they continue to
represent the balance between the demand and budget for services and the
number of Contractors supplying services on the framework. If demand or
budget does not allow for each Contractor to receive the minimum volume
then the Department reserves the right to reduce the minimum volumes at
the call-off stage.

=== Key Performance Indicators (KPIs)

[arabic, start=31]
. The KPIs in Table 5 set out the measures the Department will use to
monitor the Contractor’s performance. The KPIs will be applied to each
Call-Off Contract, with the cohort specific targets and milestones
included at the Call-Off stage. The Department reserves the right to
tailor or amend the KPIs in Table 5 for Call-Off Contracts to ensure
they reflect the needs and requirements of the specific cohort.
. *Table 5 – Key Performance Indicators*
+
[width="100%",cols="9%,35%,32%,24%",options="header",]
|===
|*KPI* |*Measure* |*Monitoring Method* |*Target and Milestone*
|*1a* a|
*Recruitment*

Recruit a minimum number of ECTs and their assigned Mentors onto the
programme.

|Monthly monitoring during the recruitment cycle as part of contract
management. |[To be determined at the Call-off stage]

|*1b* a|
*Recruitment*

Of the minimum number of ECTs and their assigned Mentors recruited onto
the programme 22% must come from schools at least 40% of their pupils
eligible for PP.

|Monthly monitoring during the recruitment cycle as part of contract
management. |[To be determined at the Call-off stage]

|*1c* a|
*Recruitment*

Of the minimum number of ECTs and their assigned Mentors recruited onto
the programme 11% must come from Local Authority Districts identified as
in the top 20% most sparse in terms of schools per hectare.

|Monthly monitoring during the recruitment cycle as part of contract
management. |[To be determined at the Call-off stage]

|*2* a|
*Retention*

A minimum of 75% of the Participants that start the training are
retained in year 1 and 2 of the delivery.

|Retention rates will be measured for each cohort from the start of the
programme through to the end of each year of the programme i.e. at the
end of year 1 and year 2. |[To be determined at the Call-off stage]

|*3* a|
*Satisfaction*

A minimum of 80% of the Participants rate the training good or above at
the end of year 1 and 2.

a|
Satisfaction will be measured through a survey completed by all
Participants at the end of each year of the programme.

The DfE will design and issue a survey for all Participants directly to
the Contractor. The Contractor shall support the DfE by administering
the surveys and returning them back to the DfE for review.

|[To be determined at the Call-off stage]
|===

. In addition to KPIs, the Department will also be measuring, on an
annual basis, the performance of the Framework Agreement, and within
that, each Contractor’s contribution in terms of;
[arabic]
.. Savings – % cohort on cohort savings on the per participant price;
.. Targeting - % achievement against recruitment forecasts;
.. Quality Assurance - % of service improvements adopted within required
timescales;
.. Quality Assurance – number of Quality and Performance recommendations
and QA failures;
.. Performance – % of Service Levels achieved; and
.. Performance – number of Service Failures.
. The Contractor will not be held to any specific targets in regards to
the measures in paragraph 32 but should the Contractor’s performance
against the measures fall consistently short of the Framework Agreement
averages or trends and the Department, acting reasonably, is satisfied
that the shortfalls are primarily due to performance issues rather than
other factors, then the Department reserves the right to request
remedial action to resolve the concerns.

=== Annex 1 to Schedule 7 – Pricing

The detailed Pricing Schedule is attached as a separate Schedule to this
Framework Agreement.

== Schedule 8 – Financial Distress

[arabic]
. *DEFINITIONS*
+
In this Schedule, the following definitions shall apply:
+
Guarantee Criteria:: In respect of the latest statutory accounts shall demonstrate that the
Contractor or Guarantor has:
+
* a current ratio (being current assets divided by current liabilities)
of one or more; and
* an acid test ratio (being current assets less stock divided by current
liabilities) of one or more; and
* a tangible net worth (being total assets less total intangible fixed
assets less total liabilities) of more than zero.

. *FINANCIAL STANDING*
[arabic]
.. If during the Term the Contractor does not meet any of the Guarantee
Criteria, at the Departments discretion, the Contractor shall procure
that:
[loweralpha]
... an Affiliate of the Contractor which at the relevant time and
thereafter meets all the Guarantee Criteria shall become a Guarantor and
shall provide a Guarantee in the form set out in Schedule 9 (Guarantee):
or
... in the event that a Group Company is not able to meet the Guarantee
Criteria the Contractor shall provide suitable alternative security in
the form of:
[lowerroman]
.... an ABI Model Form of Guarantee Bond or equivalent bond to a value of
£2,000,000 (Two Million Pounds); or
.... an alternative guarantee, the provision of funds or reserves by a third
party under guarantee, cash, deposit or escrow account as the Department
may approve (such approval not to be unreasonably withheld or delayed).
.. The Contractor shall:
[loweralpha]
... regularly monitor compliance with the Guarantee Criteria; and
... promptly notify the Department in writing following the occurrence
of a Financial Distress Event or Key Sub-contractor Financial Distress
Event or any fact, circumstance or matter which could cause a Financial
Distress Event or a Key Sub-contractor Financial Distress Event (and in
any event, ensure that such notification is made within 10 Working Days
of the date on which the Contractor first becomes aware of the Financial
Distress Event, the Key Sub-contractor Financial Distress Event or the
fact, circumstance or matter which could cause a Financial Distress
Event or a Key Sub-contractor Financial Distress Event).
. CONSEQUENCES OF A FINANCIAL DISTRESS EVENT
[arabic]
.. In the event of:
[loweralpha]
... the Contractor not meeting the Guarantee Criteria or providing a
Guarantor that meets the Guarantee Criteria, or providing alternative
security as set out in paragraph 2.1(b);
... there being a public investigation into improper financial
accounting and reporting, suspected fraud or any other impropriety of
the Contractor, or the Guarantor or any Key Sub-contractor;
... the Contractor, the Guarantor or any Key Sub-contractor committing a
material breach of covenant to its lenders;
... a Key Sub‑contractor notifying the Department that the Contractor
has not satisfied any material sums properly due under a specified
invoice and not subject to a genuine dispute; or
... any of the following:
[lowerroman]
.... commencement of any litigation against the Contractor, the Guarantor or
any Key Sub-contractor with respect to financial indebtedness greater
than £5,000,000 (Five Million Pounds) or obligations under a service
contract with a total contract value greater than £5,000,000 (Five
Million Pounds) and which is reasonably likely to be adversely
determined;
.... non-payment by the Contractor, the Guarantor or any Key Sub-contractor
of any material financial indebtedness;
.... any material financial indebtedness of the Contractor, the Guarantor or
any Key Sub-contractor becoming due as a result of an event of default;
or
.... the cancellation or suspension of any material financial indebtedness in
respect of the Contractor, the Guarantor or any Key Sub-contractor,
+
in each case which the Department reasonably believes (or would be
likely reasonably to believe) could directly impact on the continued
performance and delivery of the Services in accordance with this
Agreement;
+
then, immediately upon notification of the Financial Distress Event (or
if the Department becomes aware of the Financial Distress Event without
notification and brings the event to the attention of the Contractor),
the Contractor shall have the obligations and the Department shall have
the rights and remedies as set out in Paragraphs 3.2 to 3.3.

.. The Contractor shall (and shall procure that the Guarantor and/or any
relevant Key Sub-contractor shall):
[loweralpha]
... at the request of the Department, meet the Department as soon as
reasonably practicable (and in any event within 3 Working Days of the
initial notification (or awareness) of the Financial Distress Event or
such other period as the Department may permit and notify to the
Contractor in writing) to review the effect of the Financial Distress
Event on the continued performance and delivery of the Services in
accordance with this Agreement; and
... where the Department reasonably believes (taking into account the
discussions and any representations made under Paragraph 3.3) that the
Financial Distress Event could impact on the continued performance and
delivery of the Services in accordance with this Agreement:
[lowerroman]
.... submit to the Department a draft Financial Distress Service Continuity
Plan as soon as reasonably practicable (and in any event, within
10 Working Days of the initial notification (or awareness) of the
Financial Distress Event or such other period as the Department may
permit and notify to the Contractor in writing); and
.... provide such financial information relating to the Contractor or the
Guarantor as the Department may reasonably require.
.. The Contractor shall:
[loweralpha]
... on a regular basis (which shall not be less than monthly), review the
Financial Distress Service Continuity Plan and assess whether it remains
adequate and up to date to ensure the continued performance and delivery
of the Services in accordance with this Agreement;
... where the Financial Distress Service Continuity Plan is not adequate
or up to date in accordance with Paragraph 3.3(a), submit an updated
Financial Distress Service Continuity Plan to the Department; and
... comply with the Financial Distress Service Continuity Plan (including
any updated Financial Distress Service Continuity Plan).
.. Where the Contractor reasonably believes that the relevant Financial
Distress Event under Paragraph 3.1 (or the circumstance or matter which
has caused or otherwise led to it) no longer exists, it shall notify the
Department and the Parties may agree that the Contractor shall be
relieved of its obligations under Paragraph 3.3.

. TERMINATION RIGHTS
+
The Department shall notify the Contractor in writing of its intention
to terminate this Framework Agreement under Clause 7.4, following a
period of 30 days to allow the Contractor an opportunity to remedy the
default to the Departments satisfaction and at no cost to the
Department, if:
[loweralpha]
.. the Contractor fails to notify the Department of a Financial Distress
Event in accordance with Paragraph 2.3(b);
.. the Contractor fails to comply with the terms of the Financial
Distress Service Continuity Plan (or any updated Financial Distress
Service Continuity Plan) in accordance with Paragraph 3.3(c).

== Schedule 9 – Parent Company Guarantee

Not used.

== SCHEDULE 10: FINANCIAL REPORTS AND AUDIT RIGHTS*

=== PART A

*Financial Transparency Objectives and Open Book Data*

[arabic]
. FINANCIAL TRANSPARENCY OBJECTIVES
[arabic]
.. The Contractor shall co-operate with the Department in order to
achieve the following objectives:
+
*Understanding the Charges*
[loweralpha]
... for the Department to understand any payment sought from it by the
Contractor including an analysis of the Costs, and time spent by
Contractor Personnel in providing the Services;
... for the Department to be able to understand the impact of any proposed
Change on the Charges;

+
*Agreeing the impact of Change*
[loweralpha, start=3]
... for both Parties to agree the quantitative impact of any Changes that
affect ongoing costs and to identify how these could be mitigated and/or
reflected in the Contractors Charges;
... for both Parties to be able to review, address issues with and
re-forecast progress in relation to the provision of the Services;
+
*Continuous improvement*
[loweralpha, start=5]
... for the Parties to challenge each other with ideas for efficiency and
improvements; and
... to enable the Department to demonstrate that it is achieving value for
money for the tax payer relative to current market prices.

[arabic, start=2]
. *[.underline]#OPEN BOOK DATA#*
[arabic]
.. The Contractor shall keep or cause to be kept full and proper books
of account in relation to the provision of the Services and the entries
made therein shall be kept up-to-date at all times and shall include all
such matters and things which are usually entered in books of account in
the United Kingdom kept by persons or companies engaged in concerns of a
similar nature in accordance with best accountancy practices.
.. Such books of account, invoices, charge out rates, time sheets, or
other time recording documents kept by the Contractor in connection with
the provision of the Services and all vouchers, receipts, invoices,
orders, contractual documentation and other documentation relating to
the Services to which the Contractor is a party (“*Open Book Data*”)
shall be open to inspection by the Department or any persons appointed
to act on the Department's behalf at any reasonable time having made
prior appointment with the Contractor. The Department shall be entitled
to ask for a copy of the Open Book Data or any part thereof which
(subject to the prior payment of the Contractor's reasonable copying and
administrative charges) the Contractor shall provide within 10 Workings
Days of the Department's written request.
.. If the Department reasonably considers the Open Book Data does not
accurately represent and detail sums relating to this Agreement, and the
Services then the Contractor shall provide the Department with
documentary evidence relating to such sums and contractual obligations.
.. During the Term, and for a period of 7 years following the end of the
Term, the Contractor shall:
[loweralpha]
... maintain and retain the Open Book Data; and
... disclose and allow the Department and/or the auditor (whether internal
or external) of the Department access to the Open Book Data.

== PART B

=== Audit Rights

[arabic]
. *[.underline]#AUDIT RIGHTS#*
[arabic]
.. The Contractor shall co-operate fully and in a timely manner with any
reasonable request from time to time of the Department or any Audit
Agents and at the expense of the Contractor to provide documents, or to
procure the provision of documents, relating to this Agreement, and to
provide, or to procure the provision of, any oral or written explanation
relating to the same.
.. The Contractor shall instruct its external auditor to provide
reasonable co-operation with the Audit Agents for the purposes of
verifying financial information.
.. The Department shall during each audit comply with those security,
sites, systems and facilities operating procedures of the Contractor
that the Department deems reasonable and use its reasonable endeavours
to ensure that the conduct of each audit does not unreasonably disrupt
the Contractor or delay the provision of the Services.

== SCHEDULE 11 – ANNUAL COHORT COMPETITION INSTRUCTIONS

[arabic]
. *INTRODUCTION*
[arabic]
.. These instructions set out the process Contractors will need to
follow for the Annual Cohort Competition Award. This should be read in
conjunction with paragraphs 4.1 to 4.1.7 of Schedule 4, which sets out
the procedure for the Annual Cohort Call-off. The templates enclosed in
this Schedule will be reviewed and updated ahead of each annual Call-off
competition.
.. Each Contractor will need to complete *[.underline]#all#* the
documents listed at clause 4, following the instructions included within
the individual documents, and submit them to the DfE for review before
each Call-off is made.
. *COHORT STARTING SEPTEMBER 2021*
[arabic]
.. For the cohort starting in September 2021, Contractors will be
required to complete all the documents listed below and submit them to
the DfE by 9 April 2021.
.. The DfE intends to announce the award of the 2021 cohort Call-off
contracts on, or before, the 23 April 2021.
. *COHORTS STARTING SEPTEMBER 2022 AND BEYOND*
[arabic]
.. For subsequent cohorts the Department has set the following target
timescales:
+
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Cohort Starting* |*Call for Competition* |*Submission* |*Award*
|September 2022 |November 2021 |December 2021 |January 2022
|September 2023* |November 2022 |December 2022 |January 2023
|September 2024* |November 2023 |December 2023 |January 2024
|===

* 2023 and 2024 cohorts are subject to additional funding approvals.

.. The above timescales are indicative and therefore subject to change.
The Department will confirm the timescales ahead of each Annual Cohort
Competition.

. *ANNUAL COHORT COMPETITION DOCUMENTATION*
[arabic]
.. The Department will issue a ‘brief’ outlining the specific
priorities, targets, milestones etc for each cohort at the Call for
Competition stage.
.. Contractors will need to complete the following documents for each
Annual Cohort Competition:

* Document A – Targeting Proposal Template
* Document B – Delivery Plan Template
* Document C – Implementation Plan Template
* Document D – Communications and Marketing Plan Template
* Document E – Pricing Schedule Template

.. The documents will be updated and issued by the Department at each
Call for Competition. Contractors must complete and submit the documents
specific to that Annual Cohort Competition.

.. Template annual cohort competition documents are available as
appendixes to this schedule.

. *AWARD PROCEDURE*
[arabic]
.. The documents submitted by the Contractor will form its tender for
the Annual Cohort Competition and will be assessed against the pass/fail
criteria in the table below.
.. Should a Contractor fail any of the award criteria, the DfE will
provide written feedback in relation to the reasons why the Tender was
unsuccessful and, where in the DfE’s opinion, the reasons for failure
are minor and resolvable without significant variation to the
submission, allow the Contractor an opportunity to revise and resubmit
their tenders within a reasonable timescale. The award criteria will
then be applied to any resubmitted tenders before a final award decision
is made.
.. When awarding an Annual Cohort Competition, the DfE will initially
award the minimum recruitment target of 2,000 Participants to each
successful Contractor. Where a Contractor has proposed delivering in
excess of 2,000 Participants, and both budget and demand allow awarding
volumes in excess of the minimum recruitment targets, the DfE will award
additional recruitment volumes based on the following process:
[arabic]
... Where the total additional recruitment volumes requested does not
exceed the cohort budget and/or demand, then all Contractors will
receive the full recruitment volume as outlined in their Tender.
... Where the combined additional recruitment volumes requested exceeds
the cohort budget and/or demand, then proposals for additional volumes
will be ranked using:
[loweralpha]
.... 2021 Cohort – the framework competition final scores; or
.... 2022 Cohort and beyond – the award criteria published in the call-for
competition,
+
and awarded in order until either the demand or budget limit is met.

.. For more details on the Annual Cohort Competition procedure please
refer to Schedule 4.
+
*Table 1 – Annual Cohort Competition Criteria*
+
[width="100%",cols="34%,66%",options="header",]
|===
|*Document* |*Criteria*
|Document A – Targeting Proposal Template a|
* A clear targeting plan, including breakdowns of targeted participants
and/or schools at a Regional, Local Authority and School level.
* Demonstration that the proposed targeting approach aligns to ECF policy,
the National Roll-out requirement and the approach submitted as part of
the Providers tender.

|Document B – Delivery Plan Template a|
* Delivery plan demonstrating that proposal aligns to ECF policy, the
National Roll-out requirement and the approach submitted as part of the
Providers tender.
* Defined supply chain including specific roles and responsibilities of
each Delivery Partner and demonstration of alignment to ECF policy, the
National Roll-out requirement, and the Providers strategy for managing
Delivery Partners as submitted in the tender.

|Document C – Implementation Plan Template a|
* A clear mobilisation plan that demonstrates capacity to deliver the
service proposal to scale within the timescales.

|Document D – Communications and Marketing Plan Template a|
* A clear communications and marketing plan demonstrating that the
proposed approach offers value for money and aligns to ECF policy, the
National Roll-out requirement and the approach submitted as part of the
Providers tender.

|Document E – Pricing Schedule Template a|
* Volume banded per Participant prices and a detailed Cost Breakdown
Structure will be required to be submitted in the Pricing Schedule
supplied by the DfE. Prices must not exceed the Contractors per
participant pricing in Table 3b of Schedule 7, Part 1. Each subsequent
volume band must be priced lower than the previous band.
* 
For the purposes of the price criteria, this will be undertaken using a
‘Weighted Average Participant Price’ model. The three Volume Banded
Price Points will be weighted in the following proportion:
* Volume Band A: 60%
* Volume Band B: 30%
* Volume Band C: 10%
+
The respective price point values will be multiplied by the respective
weighting and then added together to determine a ‘Weighted Average
Participant Price’ to be used in the Price Evaluation.

* Contractors will need an ‘Average Weighted Participant Price’ within +/-
20% of the median priced successful tender.

|===
