 default: &default
   dispatchers:
     - polling_interval: 1
       batch_size: 500
   workers:
     - queues: [ mailers, migration, "*" ]
       threads: 3
       processes: 3
       polling_interval: 0.1

 development:
  <<: *default

 test:
  <<: *default

 production:
  <<: *default
