---
ENVIRONMENT_COLOUR: orange
ENVIRONMENT_PHASE_BANNER_TAG: Migration 🦔
ENVIRONMENT_PHASE_BANNER_CONTENT: This is the migration environment.
ENABLE_MIGRATION_TESTING: true
ENABLE_SCHOOLS_INTERFACE: true
ENABLE_SENTRY: true
ENABLE_PERSONAS: false
