---
ENVIRONMENT_COLOUR: pink
ENVIRONMENT_PHASE_BANNER_TAG: Review 🔍
ENVIRONMENT_PHASE_BANNER_CONTENT: This is a review application, not a real service
ENABLE_PERSONAS: true
ENABLE_SCHOOLS_INTERFACE: true
TEST_GUIDANCE: true
