---
ENVIRONMENT_COLOUR: purple
ENVIRONMENT_PHASE_BANNER_TAG: Staging 🎬
ENVIRONMENT_PHASE_BANNER_CONTENT: This is the staging environment.
ENABLE_PERSONAS: true
ENABLE_PERSONA_AVATARS: false
ENABLE_SCHOOLS_INTERFACE: true
TEST_GUIDANCE: true
ENABLE_SENTRY: true
ENABLE_BLAZER: true
